-- All migrations 001-006 in one file: paste into Supabase SQL Editor and click Run (run once on an empty project).

-- ===== migrations/001_schema.sql =====
-- Contract Tracking System — Supabase schema
-- Run in Supabase SQL Editor (or `supabase db push`). Safe to re-run on an empty project.

-- ───────────────────────── Access: Microsoft 365 sign-in + roles ─────────────────────────
-- Users sign in with Microsoft 365 (Supabase Auth "Azure" provider).
-- Their permission comes from public.user_access, matched by email.
create type public.app_role as enum ('viewer', 'user', 'confidential', 'admin');

-- Email domains allowed to sign in. Anyone else is refused unless listed in user_access.
create table public.allowed_domains (
  domain text primary key,
  default_role public.app_role not null default 'viewer'
);

-- Who may use the app and at what level. Admins manage this from Admin Tools.
create table public.user_access (
  email text primary key check (email = lower(email)),
  display_name text,
  department text,
  role public.app_role not null default 'viewer',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

-- One row per person who has actually signed in (filled automatically).
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  display_name text,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now()
);

-- On first sign-in: refuse unknown domains, create the profile, and give new
-- company users the domain's default role.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_name text := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(v_email, '@', 1));
  v_default public.app_role;
begin
  if not exists (select 1 from public.user_access where email = v_email) then
    select default_role into v_default from public.allowed_domains where domain = split_part(v_email, '@', 2);
    if v_default is null then
      raise exception 'Email % is not allowed to use this system', v_email;
    end if;
    insert into public.user_access (email, display_name, role) values (v_email, v_name, v_default);
  end if;
  insert into public.profiles (id, email, display_name, last_sign_in_at)
  values (new.id, v_email, v_name, now());
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.handle_user_sign_in()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.profiles set last_sign_in_at = new.last_sign_in_at where id = new.id;
  return new;
end $$;

create trigger on_auth_user_sign_in
  after update of last_sign_in_at on auth.users
  for each row execute function public.handle_user_sign_in();

-- Role helpers used by RLS policies. An inactive or unlisted user has no role.
create or replace function public.current_app_role()
returns public.app_role language sql stable security definer set search_path = public as $$
  select ua.role
  from public.profiles p
  join public.user_access ua on ua.email = p.email
  where p.id = auth.uid() and ua.active
$$;

create or replace function public.role_level(r public.app_role)
returns int language sql immutable as $$
  select case r when 'viewer' then 1 when 'user' then 2 when 'confidential' then 3 when 'admin' then 4 end
$$;

create or replace function public.has_level(min_level int)
returns boolean language sql stable as $$
  select coalesce(public.role_level(public.current_app_role()) >= min_level, false)
$$;

-- What the signed-in user can see about themselves (used by the app after login)
create or replace function public.my_access()
returns table (email text, display_name text, role public.app_role, active boolean)
language sql stable security definer set search_path = public as $$
  select ua.email, coalesce(ua.display_name, p.display_name), ua.role, ua.active
  from public.profiles p join public.user_access ua on ua.email = p.email
  where p.id = auth.uid()
$$;

-- ───────────────────────── Master data ─────────────────────────
create table public.departments (
  name text primary key,
  code text not null,
  active boolean not null default true
);

create table public.people (
  name text primary key,
  department text,
  email text,
  line_user_id text,
  active boolean not null default true
);

create table public.contract_types (
  id bigint generated by default as identity primary key,
  classification text not null,
  type text not null,
  sub_type text default '',
  sla int not null default 20,
  active boolean not null default true
);

create table public.action_sla (
  action text primary key,
  description text,
  sla int not null,
  rule text,
  active boolean not null default true
);

-- ───────────────────────── Contracts ─────────────────────────
create table public.contracts (
  id text primary key,
  name text not null,
  department text,
  owner text,
  classification text,
  type text,
  sub_type text,
  vendor text,
  stage text not null default 'Draft Created',
  cycle int not null default 1,
  returns int not null default 0,
  station_from text,
  station_to text,
  station_in date,
  add_case_date date not null default current_date,
  due_date date,
  system_due date,
  total_sla int,
  remark text,
  access_level text not null default 'Normal' check (access_level in ('Normal', 'Confidential')),
  status text not null default 'Open' check (status in ('Open', 'Closed', 'Cancelled')),
  closed_at date,
  close_reason text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.contract_logs (
  id bigint generated by default as identity primary key,
  contract_id text not null references public.contracts (id) on delete cascade,
  log_no int not null,
  cycle int not null default 1,
  action text,
  from_person text,
  to_person text,
  in_date date,
  out_date date,
  sla int,
  reason text,
  approval text,
  updated_by text,
  updated_at timestamptz not null default now()
);
create index contract_logs_contract_idx on public.contract_logs (contract_id, log_no);

create table public.due_date_requests (
  id bigint generated by default as identity primary key,
  contract_id text not null references public.contracts (id) on delete cascade,
  requested_due date not null,
  reason text,
  requested_by text,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  final_due date,
  decided_by text,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create trigger contracts_touch before update on public.contracts
  for each row execute function public.touch_updated_at();
create trigger user_access_touch before update on public.user_access
  for each row execute function public.touch_updated_at();

-- ───────────────────────── Row Level Security ─────────────────────────
alter table public.profiles enable row level security;
alter table public.user_access enable row level security;
alter table public.allowed_domains enable row level security;
alter table public.departments enable row level security;
alter table public.people enable row level security;
alter table public.contract_types enable row level security;
alter table public.action_sla enable row level security;
alter table public.contracts enable row level security;
alter table public.contract_logs enable row level security;
alter table public.due_date_requests enable row level security;

-- Access tables: users read their own row; admin manages everything
create policy profiles_read on public.profiles for select using (id = auth.uid() or public.has_level(4));
create policy user_access_read on public.user_access for select
  using (public.has_level(4) or email = (select p.email from public.profiles p where p.id = auth.uid()));
create policy user_access_admin on public.user_access for all using (public.has_level(4)) with check (public.has_level(4));
create policy allowed_domains_admin on public.allowed_domains for all using (public.has_level(4)) with check (public.has_level(4));

-- Master data: any signed-in user reads; admin writes
do $$
declare t text;
begin
  foreach t in array array['departments', 'people', 'contract_types', 'action_sla'] loop
    execute format('create policy %I_read on public.%I for select using (public.has_level(1))', t, t);
    execute format('create policy %I_admin_write on public.%I for all using (public.has_level(4)) with check (public.has_level(4))', t, t);
  end loop;
end $$;

-- Contracts: confidential rows only for level 3+ ; writes for level 2+ ; delete admin only
create policy contracts_read on public.contracts for select
  using (public.has_level(1) and (access_level = 'Normal' or public.has_level(3)));
create policy contracts_insert on public.contracts for insert
  with check (public.has_level(2) and (access_level = 'Normal' or public.has_level(3)));
create policy contracts_update on public.contracts for update
  using (public.has_level(2) and (access_level = 'Normal' or public.has_level(3)));
create policy contracts_delete on public.contracts for delete using (public.has_level(4));

-- Logs follow the visibility of their contract
create policy logs_read on public.contract_logs for select
  using (exists (select 1 from public.contracts c where c.id = contract_id));
create policy logs_insert on public.contract_logs for insert
  with check (public.has_level(2) and exists (select 1 from public.contracts c where c.id = contract_id));
create policy logs_admin on public.contract_logs for all using (public.has_level(4)) with check (public.has_level(4));

-- Due date requests: level 2+ create; admin decides
create policy ddr_read on public.due_date_requests for select
  using (exists (select 1 from public.contracts c where c.id = contract_id));
create policy ddr_insert on public.due_date_requests for insert with check (public.has_level(2));
create policy ddr_admin on public.due_date_requests for update using (public.has_level(4));

-- ===== migrations/002_seed.sql =====
-- Seed data (from the original dashboard). Run after 001_schema.sql.
begin;
insert into public.departments (name, code, active) values
  ('Administration', 'ADMIN', true),
  ('Business Development', 'BD', true),
  ('Finance', 'FIN', true),
  ('IT', 'IT', true),
  ('Legal', 'LEGAL', true),
  ('Marketing', 'MKT', true),
  ('Operation', 'OP', true),
  ('Procurement', 'PC', true),
  ('Project Manager', 'PM', true)
on conflict do nothing;
insert into public.people (name, department, email, active) values
  ('Pavarit Im-em (Dome)', 'Business Development', 'pavarit.i@turtle23.com', true),
  ('Supakorn Teerawutthiporn (PJ)', 'Business Development', 'supakorn.t@turtle23.com', true),
  ('Atsanai Banmai (Bank)', 'Finance', 'atsanai.b@turtle23.com', true),
  ('Teerapong Yaowalux (Pong)', 'Finance', 'teerapong.y@turtle23.com', true),
  ('Trithana Niramis (Golf)', 'Finance', 'trithana.n@turtle23.com', true),
  ('Kawinphop Champee (Boss)', 'IT', 'kawinphop.c@turtle23.com', true),
  ('Thotsaporn Phupha (Ra)', 'IT', 'thotsaporn.p@turtle23.com', true),
  ('Nattanai Saranpumidech (Ohm)', 'Administration', 'nattanai.s@turtle23.com', true),
  ('Sarocha Khamparnonda (Bee Bee)', 'Administration', 'sarocha.k@turtle23.com', true),
  ('Siwaporn Iamwiboon (Grace)', 'Legal', 'siwaporn.i@turtle23.com', true),
  ('Chanthipapha Sopanaphimon (Bow)', 'Marketing', 'chanthipapha.s@turtle23.com', true),
  ('Jiraphorn Sukhasawang (Faii)', 'Marketing', 'jiraphorn.s@turtle23.com', true),
  ('Nada Rod-in (Da)', 'Marketing', 'nada.r@turtle23.com', true),
  ('Nithita Aroonchote (Ploy)', 'Marketing', 'nithita.a@turtle23.com', true),
  ('Panphop Udomsinkul (Pap)', 'Marketing', 'panphop.u@turtle23.com', true),
  ('Pattarat Piamsin (Mind)', 'Marketing', 'pattarat.p@turtle23.com', true),
  ('Pijitporn Atjima-anan (Mod)', 'Marketing', 'pijitporn.a@turtle23.com', true),
  ('Saowaros Ratchatanawin (Ky)', 'Marketing', 'saowaros.r@turtle23.com', true),
  ('Preeyapas Srinon (Nan)', 'Operation', 'preeyapas.s@turtle23.com', true),
  ('Ratchaneekul Yamkate (Koy)', 'Operation', 'ratchaneekul.y@turtle23.com', true),
  ('Ritthasap Nutthaachakan (Ning)', 'Operation', 'ritthasap.n@turtle23.com', true),
  ('Jadsadaraj Charoeanwerapong (Tong)', 'Procurement', 'jadsadaraj.c@turtle23.com', true),
  ('Patcharaporn Sayayon (Nan Chopper)', 'Procurement', 'patcharaporn.s@turtle23.com', true),
  ('Uraiwan Julratphan (Wan)', 'Procurement', 'uraiwan.j@turtle23.com', true),
  ('Rawisara Teerapakornkul (Star)', 'Project Management', 'rawisara.t@turtle23.com', true),
  ('Tanapat Noisiri (Nutt)', 'Project Management', 'tanapat.n@turtle23.com', true),
  ('Wassana Laam (Ying)', 'Project Management', 'wassana.l@turtle23.com', true)
on conflict do nothing;
insert into public.contract_types (classification, type, sub_type, sla, active) values
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Agreement / สัญญาเช่า', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement / สัญญาเช่าช่วง', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Asset Agreement / สัญญาเช่าทรัพย์สิน', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Rental Agreement / สัญญาเช่าทั่วไป', 22, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Service Agreement / สัญญาให้บริการ', null, 22, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', null, 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Sale and Purchase Agreement / สัญญาซื้อขาย', null, 24, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Outsourcing Agreement / สัญญาจ้าง', null, 24, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Consultancy Agreement / สัญญาให้คำปรึกษา', 24, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Confidentiality Agreement / สัญญารักษาความลับ', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Others / อื่น ๆ', null, 20, true),
  ('Confidential / สัญญาลับ', 'Preliminary Agreement / ข้อตกลงเบื้องต้น', 'Memorandum of Understanding / บันทึกความเข้าใจ', 24, true),
  ('Confidential / สัญญาลับ', 'Preliminary Agreement / ข้อตกลงเบื้องต้น', 'Term Sheet / เอกสารสรุปเงื่อนไขเบื้องต้น', 24, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Consultancy Agreement / สัญญาให้คำปรึกษา', 24, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Confidentiality Agreement / สัญญารักษาความลับ', 20, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement / สัญญาบริหารจัดการ', 24, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Loan Agreement / สัญญาเงินกู้', 28, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Mergers and Acquisitions Agreement / สัญญาการควบรวมและซื้อกิจการ', 28, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Shareholders’ Agreement / สัญญาระหว่างผู้ถือหุ้น', 28, true),
  ('Confidential / สัญญาลับ', 'Others / อื่น ๆ', null, 20, true)
on conflict do nothing;
insert into public.action_sla (action, description, sla, rule, active) values
  ('Submit to Review', 'ส่งสัญญาเข้าสู่กระบวนการตรวจสอบ', 7, '7 วันทำการ (เริ่มเมื่อ Add Case)', true),
  ('Return', 'ส่งสัญญากลับเพื่อแก้ไขหรือเพิ่มเติมข้อมูล', 3, '3 วันทำการ (เมื่อได้รับ Return)', true),
  ('Resubmit', 'ส่งสัญญากลับเข้าสู่กระบวนการตรวจสอบอีกครั้งหลังแก้ไข', 5, '5 วันทำการ (เมื่อได้รับ Resubmit)', true),
  ('Forward', 'ส่งต่อสัญญาไปยังหน่วยงานหรือผู้รับผิดชอบลำดับถัดไป', 5, '5 วันทำการ (เมื่อได้รับ Forward)', true)
on conflict do nothing;
insert into public.contracts (id, name, department, owner, classification, type, sub_type, vendor, stage, cycle, returns, station_from, station_to, station_in, add_case_date, due_date, system_due, total_sla, remark, access_level, status) values
  ('CT-N-OP-001', 'Sub Lease Agreement - 3 fl Capri', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement', 'Otto - MPZ', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-21', '2026-04-21', '2026-05-19', '2026-05-19', 20, 'Place: 3 fl Capri | Source Status: In Process | Legal Status: Finalized by Legal | Latest Action: K. Henry will support to talk with K. Otto. | Note: sign quotation instead of agreement', 'Normal', 'Open'),
  ('CT-N-OP-002', 'Lease Asset / Amendment - BLY-T10', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Asset / Amendment', 'BLY-T10', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', '2026-02-05', '2026-03-05', '2026-03-05', 20, 'Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L20-69 | Received: 05 Feb 2026 | Latest Action: Final signing process by OP/will send to K. Todd for signing first. Chef Ton sign back by 12 June 2026 | Note: old period, Not yet received the signed copy. sent to chef Ton 19 Feb', 'Normal', 'Open'),
  ('CT-N-OP-003', 'Sub Lease Agreement - BLY-FSQ', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement', 'BLY-FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-30', '2026-03-30', '2028-10-31', '2026-04-27', 20, 'Source Status: In Process | Legal Status: Awaiting information in SA | Legal Tracking: L64-69 | Received: 30 Mar 2026 | Target: 13 Apr 2026 | Legal Done: 12 Mar 2026 | Latest Action: Chef Ton''s review | Note: new period, 1 Nov 25 - 31 Oct 28', 'Normal', 'Open'),
  ('CT-N-OP-004', 'Sub Lease Agreement - winwin-FSQ', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement', 'winwin-FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-13', '2026-03-13', '2028-10-31', '2026-04-10', 20, 'Source Status: In Process | Legal Status: Awaiting information in SA | Legal Tracking: L48-69 | Received: 13 Mar 2026 | Target: 27 Mar 2026 | Legal Done: 20 Mar 2026 | Latest Action: Sent to Tenant for reviewing./ As checked with K. Gee, he sent to Legal BTS for reviewing. | Note: new period, 1 Nov 25 - 31 Oct 28', 'Normal', 'Open'),
  ('CT-N-OP-005', 'Lease Asset / Amendment - BK Salon', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Asset / Amendment', 'BLY-T3', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-16', '2026-04-16', '2026-05-14', '2026-05-14', 20, 'Place: BK Salon | Source Status: In Process | Legal Status: Awaiting asset information | Legal Tracking: L58-69 | Received: 16 Apr 2026 | Target: 30 Apr 2026 | Latest Action: Final by legal, OP confirm the terms and conditions, Sent to Tenant on 19 June 2026 | Note: the name should b T3, due to the exceution date is on 1 Apr 25 (Back date)', 'Normal', 'Open'),
  ('CT-N-OP-006', 'Lease Asset / Amendment - Gowin', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Asset / Amendment', 'BLY - FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', '2026-02-05', '2026-03-05', '2026-03-05', 20, 'Place: Gowin | Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L22-69 | Received: 05 Feb 2026 | Target: 19 Feb 2026 | Legal Done: 06 Mar 2026 | Latest Action: USER - To send agreement to counterparty', 'Normal', 'Open'),
  ('CT-N-OP-007', 'Lease Agreement - Gowin', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Agreement', 'CM Gold (Jimmy) - FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-20', '2026-03-20', '2026-04-17', '2026-04-17', 20, 'Place: Gowin | Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L63-69 | Received: 20 Mar 2026 | Target: 03 Apr 2026 | Legal Done: 31 Mar 2026 | Latest Action: USER - To send agreement to counterparty/ Got review from Tenant, will send to Legal on 20May26/ Agreement will be sent by 15 June 2026', 'Normal', 'Open'),
  ('CT-N-OP-008', 'Service - Lawoi''', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service', 'TTH-Grab', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-10', '2026-02-10', '2026-03-12', '2026-03-12', 22, 'Place: Lawoi'' | Source Status: In Process | Legal Status: Awaiting further information | Received: 10 Feb 2026 | Target: 24 Feb 2026 | Legal Done: 10 Feb 2026 | Latest Action: On process of singing, will sent to LAWOI by 24 June 2026', 'Normal', 'Open'),
  ('CT-N-IT-001', 'Reservation System - Kappo S38', 'IT', 'Kawinphop Champee (Boss)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Reservation Service Agreement', 'Weeloy - T5', 'Draft Created', 1, 0, 'Kawinphop Champee (Boss)', 'Siwaporn Iamwiboon (Grace)', '2026-02-23', '2026-02-23', '2026-03-25', '2026-03-25', 22, '- เนื่องจาก memo ที่นำส่งมีการลงนามไม่ครบสมบูรณ์ ดังนั้น ขอให้จัดส่งให้ครบถ้วน
- วันที่ของสัญญาจะขอให้เว้นว่างไว้ 
- ขอให้พิจารณาวันตามข้อ 6.1 ว่ายังเป็นวันเริ่มต้น 11 April 26 อยู่หรือไม่ เนื่องจากเลยระยะเวลาดังกล่าวมาแล้ว
- เนื่องจากมีการนำข้อมูลส่วนบุคคลมาใช้ในหลายส่วน ขอให้ทำแบบ flow การใช้ข้อมูลตามที่กำหนดในสัญญา และแบบฟอร์มการส่งตรวจ pdpa', 'Normal', 'Open'),
  ('CT-N-BD-001', 'Interior Design Agreement - Roaster Coffee', 'Business Development', 'Supakorn Teerawutthiporn (PJ)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Interior Design Agreement', 'T5 - PAC', 'Draft Created', 1, 0, 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-03-19', '2026-03-19', '2026-04-22', '2026-04-22', 24, 'Place: Roaster Coffee | Source Status: In Process | Received: 19 Mar 2026 | Target: 02 Apr 2026 | Latest Action: Final signing process by BD', 'Normal', 'Open'),
  ('CT-N-BD-002', 'No.1749 - Roaster Coffee', 'Business Development', 'Supakorn Teerawutthiporn (PJ)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Agreement', 'T5-WBKK', 'Draft Created', 1, 0, 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-04-30', '2026-04-30', '2026-05-28', '2026-05-28', 20, 'Place: Roaster Coffee | Source Status: In Process | Legal Status: Awaiting further information | Received: 30 Apr 2026 | Latest Action: Final signing process by BD', 'Normal', 'Open'),
  ('CT-N-MKT-001', 'Consultancy Agreement - Unicorn Bldg', 'Marketing', 'Nithita Aroonchote (Ploy)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Consultancy Agreement', 'T23-Kamkoong', 'Draft Created', 1, 0, 'Nithita Aroonchote (Ploy)', 'Nithita Aroonchote (Ploy)', '2026-04-09', '2026-04-09', '2026-05-13', '2026-05-13', 24, 'Place: Unicorn Bldg | Source Status: In Process | Legal Status: Final signing process by MKT | Legal Tracking: L70-69 | Received: 09 Apr 2026 | Target: 23 Apr 2026 | Legal Done: 27 Apr 2026 | Latest Action: Final signing process by MKT', 'Normal', 'Open'),
  ('CT-N-OP-009', 'Laundry Service - Baan Turtle BKK', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Laundry Service', 'PVE-FSQ', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-08', '2026-04-08', '2026-05-08', '2026-05-08', 22, 'Place: Baan Turtle BKK | Source Status: In Process | Legal Status: Finalized by Legal | Received: 08 Apr 2026 | Target: 22 Apr 2026 | Note: K. Koy', 'Normal', 'Open'),
  ('CT-N-ADMIN-001', 'House Keeper - T23 office', 'Administration', 'Nattanai Saranpumidech (Ohm)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement', 'T23-SCS', 'Draft Created', 1, 0, 'Nattanai Saranpumidech (Ohm)', 'Nattanai Saranpumidech (Ohm)', '2026-04-16', '2026-04-16', '2026-05-18', '2026-05-18', 22, 'Place: T23 office | Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L76-69 | Received: 16 Apr 2026 | Target: 30 Apr 2026 | Legal Done: 21 Apr 2026', 'Normal', 'Open'),
  ('CT-N-OP-010', 'Secirity Guard - BK Salon', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement', 'FSQ - LSS', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-24', '2026-04-24', '2026-05-26', '2026-05-26', 22, 'Place: BK Salon | Source Status: In Process | Received: 24 Apr 2026 | Latest Action: sent agreement to supplier for issuing and signing contract by 9 June 2026', 'Normal', 'Open'),
  ('CT-N-MKT-002', 'MKT services - BTSV', 'Marketing', 'Pattarat Piamsin (Mind)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Consultancy Agreement', 'T23 - MCL', 'Draft Created', 1, 0, 'Pattarat Piamsin (Mind)', 'Pattarat Piamsin (Mind)', '2026-05-21', '2026-05-21', '2026-06-24', '2026-06-24', 24, 'Place: BTSV | Source Status: In Process | Received: 21 May 2026', 'Normal', 'Open'),
  ('CT-N-OP-011', 'Lift service - Baan Turtle', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement with equipment', 'FSQ - Cibes', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', '2026-05-25', '2026-06-24', '2026-06-24', 22, 'Place: Baan Turtle | Source Status: In Process | Received: 25 May 2026', 'Normal', 'Open'),
  ('CT-N-OP-012', 'Lift service - Baan Turtle', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement without equipment', 'FSQ - Cibes', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', '2026-05-25', '2026-06-24', '2026-06-24', 22, 'Place: Baan Turtle | Source Status: In Process | Received: 25 May 2026', 'Normal', 'Open'),
  ('CT-N-OP-013', 'Equipments - Lawoi''', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Eqipment lease agreement', 'KTT - Saha', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', '2026-05-25', '2026-06-22', '2026-06-22', 20, 'Place: Lawoi'' | Source Status: In Process | Received: 25 May 2026', 'Normal', 'Open'),
  ('CT-N-MKT-003', 'cross charge', 'Marketing', 'Pijitporn Atjima-anan (Mod)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Consultancy Agreement', 'T23 - Alpea', 'Draft Created', 1, 0, 'Pijitporn Atjima-anan (Mod)', 'Pijitporn Atjima-anan (Mod)', '2026-06-05', '2026-06-05', '2026-07-09', '2026-07-09', 24, 'Source Status: In Process | Legal Tracking: L100-69 | Received: 05 Jun 2026 | Latest Action: Final signing process by MKT', 'Normal', 'Open'),
  ('CT-N-OP-014', 'Lease Agreement/ Amendment - Baan Turtle', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Agreement/ Amendment', 'T23 - T10', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-04', '2026-06-04', '2026-07-02', '2026-07-02', 20, 'Place: Baan Turtle | Source Status: In Process | Received: 04 Jun 2026', 'Normal', 'Open'),
  ('CT-N-OP-015', 'PCS - Baan Turtle Phuket', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Security service agreement', 'T23', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', '2026-06-23', '2026-07-23', '2026-07-23', 22, 'Place: Baan Turtle Phuket | Source Status: In Process | Received: 23 Jun 2026', 'Normal', 'Open'),
  ('CT-N-OP-016', 'Sakeseeker - Capricci', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Commercial Agreement / สัญญาทางธุรกิจ', 'SAKE Playground event', 'Mammapazza', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', '2026-06-23', '2026-07-27', '2026-07-27', 24, 'Place: Capricci | Source Status: In Process | Received: 23 Jun 2026', 'Normal', 'Open'),
  ('CT-C-FIN-001', 'Management Agreement - Sathorn 10 Project', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - FSQ', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Sathorn 10 Project | Source Status: In Process | Legal Tracking: L99-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-002', 'Management Agreement - Baan Turtle', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - FSQ', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Baan Turtle | Source Status: In Process | Legal Tracking: L106-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-003', 'Management Agreement - Sathu Pradit', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - FSQ', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Sathu Pradit | Source Status: In Process | Legal Tracking: L107-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-004', 'Management Agreement - Chan Kao', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - WBKK', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Chan Kao | Source Status: In Process | Legal Tracking: L108-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-005', 'Management Agreement - Yenakart', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - WBKK', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Yenakart | Source Status: In Process | Legal Tracking: L109-69 | Received: 15 May 2026', 'Confidential', 'Open')
on conflict do nothing;
insert into public.contract_logs (contract_id, log_no, cycle, action, from_person, to_person, in_date, out_date, sla, reason, approval, updated_by, updated_at) values
  ('CT-N-OP-001', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-21', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-002', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-003', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-30', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-004', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-13', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-005', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-16', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-006', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-007', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-20', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-008', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-10', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-IT-001', 1, 1, 'Draft Created', 'Kawinphop Champee (Boss)', 'Siwaporn Iamwiboon (Grace)', '2026-02-23', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-BD-001', 1, 1, 'Draft Created', 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-03-19', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-BD-002', 1, 1, 'Draft Created', 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-04-30', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-MKT-001', 1, 1, 'Draft Created', 'Nithita Aroonchote (Ploy)', 'Nithita Aroonchote (Ploy)', '2026-04-09', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-009', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-08', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-ADMIN-001', 1, 1, 'Draft Created', 'Nattanai Saranpumidech (Ohm)', 'Nattanai Saranpumidech (Ohm)', '2026-04-16', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-010', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-24', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-MKT-002', 1, 1, 'Draft Created', 'Pattarat Piamsin (Mind)', 'Pattarat Piamsin (Mind)', '2026-05-21', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-011', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-012', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-013', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-001', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-MKT-003', 1, 1, 'Draft Created', 'Pijitporn Atjima-anan (Mod)', 'Pijitporn Atjima-anan (Mod)', '2026-06-05', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-014', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-04', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-002', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-003', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-004', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-005', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-015', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-016', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z')
on conflict do nothing;
insert into public.allowed_domains (domain, default_role) values ('turtle23.com', 'viewer') on conflict do nothing;
-- Everyone in the people list starts as viewer; promote people from Admin Tools.
insert into public.user_access (email, display_name, department, role, active) values
  ('pavarit.i@turtle23.com', 'Pavarit Im-em (Dome)', 'Business Development', 'viewer', true),
  ('supakorn.t@turtle23.com', 'Supakorn Teerawutthiporn (PJ)', 'Business Development', 'viewer', true),
  ('atsanai.b@turtle23.com', 'Atsanai Banmai (Bank)', 'Finance', 'viewer', true),
  ('teerapong.y@turtle23.com', 'Teerapong Yaowalux (Pong)', 'Finance', 'viewer', true),
  ('trithana.n@turtle23.com', 'Trithana Niramis (Golf)', 'Finance', 'viewer', true),
  ('kawinphop.c@turtle23.com', 'Kawinphop Champee (Boss)', 'IT', 'viewer', true),
  ('thotsaporn.p@turtle23.com', 'Thotsaporn Phupha (Ra)', 'IT', 'viewer', true),
  ('nattanai.s@turtle23.com', 'Nattanai Saranpumidech (Ohm)', 'Administration', 'viewer', true),
  ('sarocha.k@turtle23.com', 'Sarocha Khamparnonda (Bee Bee)', 'Administration', 'viewer', true),
  ('siwaporn.i@turtle23.com', 'Siwaporn Iamwiboon (Grace)', 'Legal', 'viewer', true),
  ('chanthipapha.s@turtle23.com', 'Chanthipapha Sopanaphimon (Bow)', 'Marketing', 'viewer', true),
  ('jiraphorn.s@turtle23.com', 'Jiraphorn Sukhasawang (Faii)', 'Marketing', 'viewer', true),
  ('nada.r@turtle23.com', 'Nada Rod-in (Da)', 'Marketing', 'viewer', true),
  ('nithita.a@turtle23.com', 'Nithita Aroonchote (Ploy)', 'Marketing', 'viewer', true),
  ('panphop.u@turtle23.com', 'Panphop Udomsinkul (Pap)', 'Marketing', 'viewer', true),
  ('pattarat.p@turtle23.com', 'Pattarat Piamsin (Mind)', 'Marketing', 'viewer', true),
  ('pijitporn.a@turtle23.com', 'Pijitporn Atjima-anan (Mod)', 'Marketing', 'viewer', true),
  ('saowaros.r@turtle23.com', 'Saowaros Ratchatanawin (Ky)', 'Marketing', 'viewer', true),
  ('preeyapas.s@turtle23.com', 'Preeyapas Srinon (Nan)', 'Operation', 'viewer', true),
  ('ratchaneekul.y@turtle23.com', 'Ratchaneekul Yamkate (Koy)', 'Operation', 'viewer', true),
  ('ritthasap.n@turtle23.com', 'Ritthasap Nutthaachakan (Ning)', 'Operation', 'viewer', true),
  ('jadsadaraj.c@turtle23.com', 'Jadsadaraj Charoeanwerapong (Tong)', 'Procurement', 'viewer', true),
  ('patcharaporn.s@turtle23.com', 'Patcharaporn Sayayon (Nan Chopper)', 'Procurement', 'viewer', true),
  ('uraiwan.j@turtle23.com', 'Uraiwan Julratphan (Wan)', 'Procurement', 'viewer', true),
  ('rawisara.t@turtle23.com', 'Rawisara Teerapakornkul (Star)', 'Project Management', 'viewer', true),
  ('tanapat.n@turtle23.com', 'Tanapat Noisiri (Nutt)', 'Project Management', 'viewer', true),
  ('wassana.l@turtle23.com', 'Wassana Laam (Ying)', 'Project Management', 'viewer', true)
on conflict do nothing;
commit;

-- ===== migrations/003_entra_roles.sql =====
-- Backend permission management after Microsoft Entra ID is linked.
-- Run after 001_schema.sql and 002_seed.sql.
--
-- How a user's Access Level is decided at every Microsoft sign-in:
--   1. If the Entra ID token carries an App Role (or group id) listed in entra_role_mappings,
--      the highest mapped level wins and user_access.source becomes 'entra'.
--   2. Otherwise the level set by an Admin in user_access stays as it is (source 'manual').
--   3. Unknown users from an allowed domain start as that domain's default level.
-- Every change to user_access is written to access_audit.

-- ───────────── Entra App Role / group → Access Level ─────────────
create table public.entra_role_mappings (
  claim_value text primary key,             -- App Role value (e.g. Contract.Admin) or group object id
  role public.app_role not null,
  note text
);

insert into public.entra_role_mappings (claim_value, role, note) values
  ('Contract.Viewer', 'viewer', 'Level 1 · Contract Viewer'),
  ('Contract.User', 'user', 'Level 2 · Contract User'),
  ('Contract.Confidential', 'confidential', 'Level 3 · Confidential User'),
  ('Contract.Admin', 'admin', 'Level 4 · System Administrator')
on conflict do nothing;

alter table public.user_access
  add column if not exists source text not null default 'manual' check (source in ('manual', 'entra', 'domain'));

-- Highest level among the App Roles / groups in the user's Entra token (null when none match).
-- Supabase keeps extra ID-token claims under raw_user_meta_data.custom_claims.
create or replace function public.entra_level_for(meta jsonb)
returns public.app_role language sql stable security definer set search_path = public as $$
  select m.role
  from public.entra_role_mappings m
  where m.claim_value in (
    select jsonb_array_elements_text(coalesce(meta -> 'custom_claims' -> 'roles', meta -> 'roles', '[]'::jsonb))
    union
    select jsonb_array_elements_text(coalesce(meta -> 'custom_claims' -> 'groups', meta -> 'groups', '[]'::jsonb))
  )
  order by public.role_level(m.role) desc
  limit 1
$$;

-- First sign-in: Entra role first, then manual list, then allowed domain; anyone else is refused.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_name text := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(v_email, '@', 1));
  v_entra public.app_role := public.entra_level_for(new.raw_user_meta_data);
  v_default public.app_role;
begin
  if v_entra is not null then
    insert into public.user_access (email, display_name, role, source) values (v_email, v_name, v_entra, 'entra')
    on conflict (email) do update set role = excluded.role, source = 'entra';
  elsif not exists (select 1 from public.user_access where email = v_email) then
    select default_role into v_default from public.allowed_domains where domain = split_part(v_email, '@', 2);
    if v_default is null then
      raise exception 'Email % is not allowed to use this system', v_email;
    end if;
    insert into public.user_access (email, display_name, role, source) values (v_email, v_name, v_default, 'domain');
  end if;
  insert into public.profiles (id, email, display_name, last_sign_in_at)
  values (new.id, v_email, v_name, now());
  return new;
end $$;

-- Later sign-ins: keep the level in step with Entra when the token carries a mapped role.
-- If the role was removed in Entra, an Entra-managed user drops back to the domain default.
create or replace function public.handle_user_sign_in()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_entra public.app_role := public.entra_level_for(new.raw_user_meta_data);
begin
  update public.profiles set last_sign_in_at = new.last_sign_in_at where id = new.id;
  if v_entra is not null then
    update public.user_access set role = v_entra, source = 'entra'
    where email = v_email and (role <> v_entra or source <> 'entra');
  else
    update public.user_access ua set role = coalesce(d.default_role, 'viewer'), source = 'domain'
    from (select default_role from public.allowed_domains where domain = split_part(v_email, '@', 2)) d
    where ua.email = v_email and ua.source = 'entra';
  end if;
  return new;
end $$;

drop trigger if exists on_auth_user_sign_in on auth.users;
create trigger on_auth_user_sign_in
  after update of last_sign_in_at, raw_user_meta_data on auth.users
  for each row execute function public.handle_user_sign_in();

-- ───────────── Audit trail ─────────────
create table public.access_audit (
  id bigint generated by default as identity primary key,
  email text not null,
  action text not null,                      -- added / changed / removed
  old_role public.app_role,
  new_role public.app_role,
  old_active boolean,
  new_active boolean,
  source text,
  changed_by text not null,
  changed_at timestamptz not null default now()
);

create or replace function public.audit_user_access()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_by text := coalesce((select email from public.profiles where id = auth.uid()), 'system / Entra sign-in');
begin
  if tg_op = 'INSERT' then
    insert into public.access_audit (email, action, new_role, new_active, source, changed_by)
    values (new.email, 'added', new.role, new.active, new.source, v_by);
  elsif tg_op = 'UPDATE' and (old.role, old.active) is distinct from (new.role, new.active) then
    insert into public.access_audit (email, action, old_role, new_role, old_active, new_active, source, changed_by)
    values (new.email, 'changed', old.role, new.role, old.active, new.active, new.source, v_by);
  elsif tg_op = 'DELETE' then
    insert into public.access_audit (email, action, old_role, old_active, source, changed_by)
    values (old.email, 'removed', old.role, old.active, old.source, v_by);
  end if;
  return coalesce(new, old);
end $$;

create trigger user_access_audit
  after insert or update or delete on public.user_access
  for each row execute function public.audit_user_access();

-- ───────────── Safety: never lose the last Admin ─────────────
create or replace function public.keep_one_admin()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- only matters when the row being changed or removed was an active Admin
  if old.role = 'admin' and old.active
     and not exists (select 1 from public.user_access where role = 'admin' and active) then
    raise exception 'At least one active Admin must remain';
  end if;
  return null;
end $$;

create constraint trigger user_access_keep_admin
  after update or delete on public.user_access
  deferrable initially deferred
  for each row execute function public.keep_one_admin();

-- An Admin edit to a level marks it as manual, so the screen shows who manages it
create or replace function public.mark_manual_change()
returns trigger language plpgsql as $$
begin
  if auth.uid() is not null and (old.role, old.active) is distinct from (new.role, new.active) and new.source = old.source then
    new.source := 'manual';
  end if;
  return new;
end $$;

create trigger user_access_mark_manual
  before update on public.user_access
  for each row execute function public.mark_manual_change();

-- ───────────── RLS ─────────────
alter table public.entra_role_mappings enable row level security;
alter table public.access_audit enable row level security;
create policy entra_role_mappings_admin on public.entra_role_mappings for all using (public.has_level(4)) with check (public.has_level(4));
create policy access_audit_admin_read on public.access_audit for select using (public.has_level(4));

-- ===== migrations/004_menu_access.sql =====
-- Menu / page access per Access Level (run after 003_entra_roles.sql).
--
--   Level 1 Viewer        Dashboard, Contracts
--   Level 2 User          Dashboard, Contracts, User Case Action
--   Level 3 Confidential  Dashboard, Contracts, Confidential, User Case Action
--   Level 4 Admin         Dashboard, Contracts, Confidential, User Case Action, Master Data, Admin Tools
--
-- The web app hides menus and blocks typed URLs; these policies make the data match.
-- Contracts, logs and due-date requests already follow these levels (001_schema.sql):
--   read Normal contracts from Level 1, Confidential from Level 3, write cases from Level 2, admin-only approvals.
-- Master Data becomes an Admin page, so Viewers no longer read the master tables.
-- Level 2-3 still read them because User Case Action fills its dropdowns from them; only Admin writes.
do $$
declare t text;
begin
  foreach t in array array['departments', 'people', 'contract_types', 'action_sla'] loop
    execute format('drop policy if exists %I_read on public.%I', t, t);
    execute format('create policy %I_read on public.%I for select using (public.has_level(2))', t, t);
  end loop;
end $$;

-- ===== migrations/005_snapshot_import.sql =====
-- 005: Import a Production Snapshot (production_snapshot.json) from Admin Tools.
-- Run after 001-004. Safe to run more than once.
--   * keeps every snapshot column that has no column of its own in `details` (jsonb)
--   * adds the Contract Name Template master (contract_templates)
--   * import_snapshot(p): Admin only, adds or updates contracts, logs, due date requests and master data
--     in ONE transaction (all or nothing). Nothing is deleted: a row is matched by its key
--     (Contract ID, Contract ID + Log No, name, ...) and updated, otherwise added.
--     Users & Roles keep their levels; people with a new email are added as Viewer.

alter table public.contracts add column if not exists details jsonb;
alter table public.contract_logs add column if not exists details jsonb;
alter table public.due_date_requests add column if not exists details jsonb;

create table if not exists public.contract_templates (
  id bigint generated by default as identity primary key,
  classification text,
  type_group text,
  sub_type text,
  name text not null,
  selection_label text,
  source_row int,
  type text,
  work_type text,
  contract_id text,
  access_level text,
  category text,
  department text,
  vendor text,
  group_name text,
  fixed_sla int,
  sla_version text,
  remark text,
  active boolean not null default true
);
create unique index if not exists contract_templates_label_key on public.contract_templates (selection_label);
create unique index if not exists contract_logs_contract_log_key on public.contract_logs (contract_id, log_no);
create unique index if not exists contract_types_key on public.contract_types (classification, type, (coalesce(sub_type, '')));
alter table public.contract_templates enable row level security;
drop policy if exists contract_templates_read on public.contract_templates;
drop policy if exists contract_templates_admin_write on public.contract_templates;
create policy contract_templates_read on public.contract_templates for select using (public.has_level(2));
create policy contract_templates_admin_write on public.contract_templates for all using (public.has_level(4)) with check (public.has_level(4));

create or replace function public.import_snapshot(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_added int;
begin
  if not public.has_level(4) then
    raise exception 'Only a System Administrator can import a snapshot';
  end if;
  if jsonb_array_length(coalesce(p -> 'contracts', '[]')) = 0 then
    raise exception 'Snapshot has no contracts';
  end if;

  insert into public.departments (name, code, active)
  select name, coalesce(code, ''), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'departments', '[]')) as x(name text, code text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (name) do update set code = excluded.code, active = excluded.active;

  insert into public.people (name, department, email, line_user_id, active)
  select name, department, nullif(lower(email), ''), nullif(line_user_id, ''), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'people', '[]')) as x(name text, department text, email text, line_user_id text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (name) do update set department = excluded.department, email = excluded.email,
    line_user_id = excluded.line_user_id, active = excluded.active;

  insert into public.contract_types (classification, type, sub_type, sla, active)
  select classification, type, coalesce(sub_type, ''), coalesce(sla, 20), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'contract_types', '[]')) as x(classification text, type text, sub_type text, sla int, active boolean)
  on conflict (classification, type, (coalesce(sub_type, ''))) do update set sub_type = excluded.sub_type, sla = excluded.sla, active = excluded.active;

  insert into public.action_sla (action, description, sla, rule, active)
  select action, description, coalesce(sla, 0), rule, coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'action_sla', '[]')) as x(action text, description text, sla int, rule text, active boolean)
  on conflict (action) do update set description = excluded.description, sla = excluded.sla, rule = excluded.rule, active = excluded.active;

  insert into public.contract_templates (classification, type_group, sub_type, name, selection_label, source_row, type, work_type,
    contract_id, access_level, category, department, vendor, group_name, fixed_sla, sla_version, remark, active)
  select classification, type_group, sub_type, name, selection_label, source_row, type, work_type,
    contract_id, access_level, category, department, vendor, group_name, fixed_sla, sla_version, remark, coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'contract_templates', '[]')) as x(classification text, type_group text, sub_type text, name text,
    selection_label text, source_row int, type text, work_type text, contract_id text, access_level text, category text, department text,
    vendor text, group_name text, fixed_sla int, sla_version text, remark text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (selection_label) do update set classification = excluded.classification, type_group = excluded.type_group,
    sub_type = excluded.sub_type, name = excluded.name, source_row = excluded.source_row, type = excluded.type,
    work_type = excluded.work_type, contract_id = excluded.contract_id, access_level = excluded.access_level,
    category = excluded.category, department = excluded.department, vendor = excluded.vendor, group_name = excluded.group_name,
    fixed_sla = excluded.fixed_sla, sla_version = excluded.sla_version, remark = excluded.remark, active = excluded.active;

  insert into public.contracts (id, name, department, owner, classification, type, sub_type, vendor, stage, cycle, returns,
    station_from, station_to, station_in, add_case_date, due_date, system_due, total_sla, remark, access_level, status,
    closed_at, close_reason, created_by, details)
  select id, name, department, owner, classification, type, sub_type, vendor, coalesce(stage, 'Draft Created'), coalesce(cycle, 1), coalesce(returns, 0),
    station_from, station_to, station_in, coalesce(add_case_date, current_date), due_date, system_due, total_sla, remark,
    coalesce(access_level, 'Normal'), coalesce(status, 'Open'), closed_at, close_reason, null, details
  from jsonb_to_recordset(p -> 'contracts') as x(id text, name text, department text, owner text, classification text, type text,
    sub_type text, vendor text, stage text, cycle int, returns int, station_from text, station_to text, station_in date,
    add_case_date date, due_date date, system_due date, total_sla int, remark text, access_level text, status text,
    closed_at date, close_reason text, details jsonb)
  on conflict (id) do update set name = excluded.name, department = excluded.department, owner = excluded.owner,
    classification = excluded.classification, type = excluded.type, sub_type = excluded.sub_type, vendor = excluded.vendor,
    stage = excluded.stage, cycle = excluded.cycle, returns = excluded.returns, station_from = excluded.station_from,
    station_to = excluded.station_to, station_in = excluded.station_in, add_case_date = excluded.add_case_date,
    due_date = excluded.due_date, system_due = excluded.system_due, total_sla = excluded.total_sla, remark = excluded.remark,
    access_level = excluded.access_level, status = excluded.status, closed_at = excluded.closed_at,
    close_reason = excluded.close_reason, details = excluded.details;

  insert into public.contract_logs (contract_id, log_no, cycle, action, from_person, to_person, in_date, out_date, sla,
    reason, approval, updated_by, updated_at, details)
  select contract_id, log_no, coalesce(cycle, 1), action, from_person, to_person, in_date, out_date, sla,
    reason, approval, updated_by, coalesce(updated_at, now()), details
  from jsonb_to_recordset(coalesce(p -> 'contract_logs', '[]')) as x(contract_id text, log_no int, cycle int, action text,
    from_person text, to_person text, in_date date, out_date date, sla int, reason text, approval text, updated_by text,
    updated_at timestamptz, details jsonb)
  on conflict (contract_id, log_no) do update set cycle = excluded.cycle, action = excluded.action,
    from_person = excluded.from_person, to_person = excluded.to_person, in_date = excluded.in_date, out_date = excluded.out_date,
    sla = excluded.sla, reason = excluded.reason, approval = excluded.approval, updated_by = excluded.updated_by,
    updated_at = excluded.updated_at, details = excluded.details;

  insert into public.due_date_requests (contract_id, requested_due, reason, requested_by, status, created_at, details)
  select contract_id, requested_due, reason, requested_by, coalesce(status, 'Pending'), coalesce(created_at, now()), details
  from jsonb_to_recordset(coalesce(p -> 'due_date_requests', '[]')) as x(contract_id text, requested_due date, reason text,
    requested_by text, status text, created_at timestamptz, details jsonb)
  -- the same request (Request ID) is only added once
  where not exists (select 1 from public.due_date_requests d where d.details ->> 'requestId' = x.details ->> 'requestId');

  -- People in the snapshot can sign in; existing accounts (and their levels) are left as they are
  insert into public.user_access (email, display_name, department, role, active)
  select lower(email), name, department, 'viewer', true
  from public.people
  where email like '%@%'
  on conflict (email) do nothing;
  get diagnostics v_added = row_count;

  return jsonb_build_object(
    'imported_contracts', jsonb_array_length(p -> 'contracts'),
    'imported_logs', jsonb_array_length(coalesce(p -> 'contract_logs', '[]')),
    'contracts', (select count(*) from public.contracts),
    'contract_logs', (select count(*) from public.contract_logs),
    'due_date_requests', (select count(*) from public.due_date_requests),
    'departments', (select count(*) from public.departments),
    'people', (select count(*) from public.people),
    'contract_types', (select count(*) from public.contract_types),
    'contract_templates', (select count(*) from public.contract_templates),
    'action_sla', (select count(*) from public.action_sla),
    'new_users', v_added);
end;
$$;

revoke all on function public.import_snapshot(jsonb) from public, anon;
grant execute on function public.import_snapshot(jsonb) to authenticated;

-- ===== migrations/006_root_level.sql =====
-- 006: Level 5 "Root System Administrator". Run after 001-005. Safe to run more than once.
--   * Level 5 (root) has every right of Level 4 plus Master Data (the only level that can edit it).
--   * Level 4 (admin) keeps Admin Tools, Users & Roles and Import, but Master Data becomes read-only
--     for it (the tables still feed the dropdowns of User Case Action).
--   * Only a Level 5 account can give or take Level 5. While nobody has Level 5 yet, a Level 4 Admin may
--     set it (so the first Root can be chosen in Users & Roles). The SQL Editor can always set it.
--   * Microsoft Entra App Roles never lower a Level 5 account.
--   * "At least one active Admin" now counts Level 4 and Level 5 together.
-- Nobody's level is changed by this script.

alter type public.app_role add value if not exists 'root';

-- r::text so this script does not need the new enum value to be committed first
create or replace function public.role_level(r public.app_role)
returns int language sql immutable as $$
  select case r::text when 'viewer' then 1 when 'user' then 2 when 'confidential' then 3 when 'admin' then 4 when 'root' then 5 end
$$;

-- ───────────── Master Data: edit = Level 5, read = Level 2+ (004) ─────────────
do $$
declare t text;
begin
  foreach t in array array['departments', 'people', 'contract_types', 'action_sla', 'contract_templates'] loop
    execute format('drop policy if exists %I_admin_write on public.%I', t, t);
    execute format('create policy %I_admin_write on public.%I for all using (public.has_level(5)) with check (public.has_level(5))', t, t);
  end loop;
end $$;

-- ───────────── Who may grant or remove Level 5 ─────────────
create or replace function public.guard_root_role()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- SQL Editor and Microsoft sign-in (no signed-in app user) are not limited here
  if auth.uid() is null or public.has_level(5) then
    return coalesce(new, old);
  end if;
  if ((tg_op <> 'INSERT' and old.role::text = 'root') or (tg_op <> 'DELETE' and new.role::text = 'root'))
     and exists (select 1 from public.user_access where role::text = 'root' and active) then
    raise exception 'Only a Root System Administrator (Level 5) can grant, change or remove Level 5';
  end if;
  return coalesce(new, old);
end $$;

drop trigger if exists user_access_guard_root on public.user_access;
create trigger user_access_guard_root
  before insert or update or delete on public.user_access
  for each row execute function public.guard_root_role();

-- ───────────── Never lose the last Admin (Level 4 or 5) ─────────────
create or replace function public.keep_one_admin()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.role::text in ('admin', 'root') and old.active
     and not exists (select 1 from public.user_access where role::text in ('admin', 'root') and active) then
    raise exception 'At least one active Admin (Level 4 or 5) must remain';
  end if;
  return null;
end $$;

-- ───────────── Entra sign-in never lowers a Level 5 account ─────────────
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_name text := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(v_email, '@', 1));
  v_entra public.app_role := public.entra_level_for(new.raw_user_meta_data);
  v_default public.app_role;
begin
  if v_entra is not null then
    insert into public.user_access (email, display_name, role, source) values (v_email, v_name, v_entra, 'entra')
    on conflict (email) do update set role = excluded.role, source = 'entra'
    where public.user_access.role::text <> 'root';
  elsif not exists (select 1 from public.user_access where email = v_email) then
    select default_role into v_default from public.allowed_domains where domain = split_part(v_email, '@', 2);
    if v_default is null then
      raise exception 'Email % is not allowed to use this system', v_email;
    end if;
    insert into public.user_access (email, display_name, role, source) values (v_email, v_name, v_default, 'domain');
  end if;
  insert into public.profiles (id, email, display_name, last_sign_in_at)
  values (new.id, v_email, v_name, now());
  return new;
end $$;

create or replace function public.handle_user_sign_in()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_entra public.app_role := public.entra_level_for(new.raw_user_meta_data);
begin
  update public.profiles set last_sign_in_at = new.last_sign_in_at where id = new.id;
  if v_entra is not null then
    update public.user_access set role = v_entra, source = 'entra'
    where email = v_email and role::text <> 'root' and (role <> v_entra or source <> 'entra');
  else
    update public.user_access ua set role = coalesce(d.default_role, 'viewer'), source = 'domain'
    from (select default_role from public.allowed_domains where domain = split_part(v_email, '@', 2)) d
    where ua.email = v_email and ua.source = 'entra' and ua.role::text <> 'root';
  end if;
  return new;
end $$;
