-- Contract Tracking System — Supabase schema
-- Run in Supabase SQL Editor (or `supabase db push`). Safe to re-run on an empty project.

-- ───────────────────────── Access: Microsoft 365 sign-in + roles ─────────────────────────
-- Users sign in with Microsoft 365 (Supabase Auth "Azure" provider).
-- Their permission comes from public.user_access, matched by email.
create type public.app_role as enum ('viewer', 'user', 'confidential', 'admin');

-- Email domains allowed to sign in. Anyone else is refused unless listed in user_access.
create table public.allowed_domains (
  domain text primary key,
  default_role public.app_role not null default 'viewer'
);

-- Who may use the app and at what level. Admins manage this from Admin Tools.
create table public.user_access (
  email text primary key check (email = lower(email)),
  display_name text,
  department text,
  role public.app_role not null default 'viewer',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

-- One row per person who has actually signed in (filled automatically).
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  display_name text,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now()
);

-- On first sign-in: refuse unknown domains, create the profile, and give new
-- company users the domain's default role.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_name text := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(v_email, '@', 1));
  v_default public.app_role;
begin
  if not exists (select 1 from public.user_access where email = v_email) then
    select default_role into v_default from public.allowed_domains where domain = split_part(v_email, '@', 2);
    if v_default is null then
      raise exception 'Email % is not allowed to use this system', v_email;
    end if;
    insert into public.user_access (email, display_name, role) values (v_email, v_name, v_default);
  end if;
  insert into public.profiles (id, email, display_name, last_sign_in_at)
  values (new.id, v_email, v_name, now());
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.handle_user_sign_in()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.profiles set last_sign_in_at = new.last_sign_in_at where id = new.id;
  return new;
end $$;

create trigger on_auth_user_sign_in
  after update of last_sign_in_at on auth.users
  for each row execute function public.handle_user_sign_in();

-- Role helpers used by RLS policies. An inactive or unlisted user has no role.
create or replace function public.current_app_role()
returns public.app_role language sql stable security definer set search_path = public as $$
  select ua.role
  from public.profiles p
  join public.user_access ua on ua.email = p.email
  where p.id = auth.uid() and ua.active
$$;

create or replace function public.role_level(r public.app_role)
returns int language sql immutable as $$
  select case r when 'viewer' then 1 when 'user' then 2 when 'confidential' then 3 when 'admin' then 4 end
$$;

create or replace function public.has_level(min_level int)
returns boolean language sql stable as $$
  select coalesce(public.role_level(public.current_app_role()) >= min_level, false)
$$;

-- What the signed-in user can see about themselves (used by the app after login)
create or replace function public.my_access()
returns table (email text, display_name text, role public.app_role, active boolean)
language sql stable security definer set search_path = public as $$
  select ua.email, coalesce(ua.display_name, p.display_name), ua.role, ua.active
  from public.profiles p join public.user_access ua on ua.email = p.email
  where p.id = auth.uid()
$$;

-- ───────────────────────── Master data ─────────────────────────
create table public.departments (
  name text primary key,
  code text not null,
  active boolean not null default true
);

create table public.people (
  name text primary key,
  department text,
  email text,
  line_user_id text,
  active boolean not null default true
);

create table public.contract_types (
  id bigint generated by default as identity primary key,
  classification text not null,
  type text not null,
  sub_type text default '',
  sla int not null default 20,
  active boolean not null default true
);

create table public.action_sla (
  action text primary key,
  description text,
  sla int not null,
  rule text,
  active boolean not null default true
);

-- ───────────────────────── Contracts ─────────────────────────
create table public.contracts (
  id text primary key,
  name text not null,
  department text,
  owner text,
  classification text,
  type text,
  sub_type text,
  vendor text,
  stage text not null default 'Draft Created',
  cycle int not null default 1,
  returns int not null default 0,
  station_from text,
  station_to text,
  station_in date,
  add_case_date date not null default current_date,
  due_date date,
  system_due date,
  total_sla int,
  remark text,
  access_level text not null default 'Normal' check (access_level in ('Normal', 'Confidential')),
  status text not null default 'Open' check (status in ('Open', 'Closed', 'Cancelled')),
  closed_at date,
  close_reason text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.contract_logs (
  id bigint generated by default as identity primary key,
  contract_id text not null references public.contracts (id) on delete cascade,
  log_no int not null,
  cycle int not null default 1,
  action text,
  from_person text,
  to_person text,
  in_date date,
  out_date date,
  sla int,
  reason text,
  approval text,
  updated_by text,
  updated_at timestamptz not null default now()
);
create index contract_logs_contract_idx on public.contract_logs (contract_id, log_no);

create table public.due_date_requests (
  id bigint generated by default as identity primary key,
  contract_id text not null references public.contracts (id) on delete cascade,
  requested_due date not null,
  reason text,
  requested_by text,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  final_due date,
  decided_by text,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create trigger contracts_touch before update on public.contracts
  for each row execute function public.touch_updated_at();
create trigger user_access_touch before update on public.user_access
  for each row execute function public.touch_updated_at();

-- ───────────────────────── Row Level Security ─────────────────────────
alter table public.profiles enable row level security;
alter table public.user_access enable row level security;
alter table public.allowed_domains enable row level security;
alter table public.departments enable row level security;
alter table public.people enable row level security;
alter table public.contract_types enable row level security;
alter table public.action_sla enable row level security;
alter table public.contracts enable row level security;
alter table public.contract_logs enable row level security;
alter table public.due_date_requests enable row level security;

-- Access tables: users read their own row; admin manages everything
create policy profiles_read on public.profiles for select using (id = auth.uid() or public.has_level(4));
create policy user_access_read on public.user_access for select
  using (public.has_level(4) or email = (select p.email from public.profiles p where p.id = auth.uid()));
create policy user_access_admin on public.user_access for all using (public.has_level(4)) with check (public.has_level(4));
create policy allowed_domains_admin on public.allowed_domains for all using (public.has_level(4)) with check (public.has_level(4));

-- Master data: any signed-in user reads; admin writes
do $$
declare t text;
begin
  foreach t in array array['departments', 'people', 'contract_types', 'action_sla'] loop
    execute format('create policy %I_read on public.%I for select using (public.has_level(1))', t, t);
    execute format('create policy %I_admin_write on public.%I for all using (public.has_level(4)) with check (public.has_level(4))', t, t);
  end loop;
end $$;

-- Contracts: confidential rows only for level 3+ ; writes for level 2+ ; delete admin only
create policy contracts_read on public.contracts for select
  using (public.has_level(1) and (access_level = 'Normal' or public.has_level(3)));
create policy contracts_insert on public.contracts for insert
  with check (public.has_level(2) and (access_level = 'Normal' or public.has_level(3)));
create policy contracts_update on public.contracts for update
  using (public.has_level(2) and (access_level = 'Normal' or public.has_level(3)));
create policy contracts_delete on public.contracts for delete using (public.has_level(4));

-- Logs follow the visibility of their contract
create policy logs_read on public.contract_logs for select
  using (exists (select 1 from public.contracts c where c.id = contract_id));
create policy logs_insert on public.contract_logs for insert
  with check (public.has_level(2) and exists (select 1 from public.contracts c where c.id = contract_id));
create policy logs_admin on public.contract_logs for all using (public.has_level(4)) with check (public.has_level(4));

-- Due date requests: level 2+ create; admin decides
create policy ddr_read on public.due_date_requests for select
  using (exists (select 1 from public.contracts c where c.id = contract_id));
create policy ddr_insert on public.due_date_requests for insert with check (public.has_level(2));
create policy ddr_admin on public.due_date_requests for update using (public.has_level(4));
