-- Seed data (from the original dashboard). Run after 001_schema.sql.
begin;
insert into public.departments (name, code, active) values
  ('Administration', 'ADMIN', true),
  ('Business Development', 'BD', true),
  ('Finance', 'FIN', true),
  ('IT', 'IT', true),
  ('Legal', 'LEGAL', true),
  ('Marketing', 'MKT', true),
  ('Operation', 'OP', true),
  ('Procurement', 'PC', true),
  ('Project Manager', 'PM', true)
on conflict do nothing;
insert into public.people (name, department, email, active) values
  ('Pavarit Im-em (Dome)', 'Business Development', 'pavarit.i@turtle23.com', true),
  ('Supakorn Teerawutthiporn (PJ)', 'Business Development', 'supakorn.t@turtle23.com', true),
  ('Atsanai Banmai (Bank)', 'Finance', 'atsanai.b@turtle23.com', true),
  ('Teerapong Yaowalux (Pong)', 'Finance', 'teerapong.y@turtle23.com', true),
  ('Trithana Niramis (Golf)', 'Finance', 'trithana.n@turtle23.com', true),
  ('Kawinphop Champee (Boss)', 'IT', 'kawinphop.c@turtle23.com', true),
  ('Thotsaporn Phupha (Ra)', 'IT', 'thotsaporn.p@turtle23.com', true),
  ('Nattanai Saranpumidech (Ohm)', 'Administration', 'nattanai.s@turtle23.com', true),
  ('Sarocha Khamparnonda (Bee Bee)', 'Administration', 'sarocha.k@turtle23.com', true),
  ('Siwaporn Iamwiboon (Grace)', 'Legal', 'siwaporn.i@turtle23.com', true),
  ('Chanthipapha Sopanaphimon (Bow)', 'Marketing', 'chanthipapha.s@turtle23.com', true),
  ('Jiraphorn Sukhasawang (Faii)', 'Marketing', 'jiraphorn.s@turtle23.com', true),
  ('Nada Rod-in (Da)', 'Marketing', 'nada.r@turtle23.com', true),
  ('Nithita Aroonchote (Ploy)', 'Marketing', 'nithita.a@turtle23.com', true),
  ('Panphop Udomsinkul (Pap)', 'Marketing', 'panphop.u@turtle23.com', true),
  ('Pattarat Piamsin (Mind)', 'Marketing', 'pattarat.p@turtle23.com', true),
  ('Pijitporn Atjima-anan (Mod)', 'Marketing', 'pijitporn.a@turtle23.com', true),
  ('Saowaros Ratchatanawin (Ky)', 'Marketing', 'saowaros.r@turtle23.com', true),
  ('Preeyapas Srinon (Nan)', 'Operation', 'preeyapas.s@turtle23.com', true),
  ('Ratchaneekul Yamkate (Koy)', 'Operation', 'ratchaneekul.y@turtle23.com', true),
  ('Ritthasap Nutthaachakan (Ning)', 'Operation', 'ritthasap.n@turtle23.com', true),
  ('Jadsadaraj Charoeanwerapong (Tong)', 'Procurement', 'jadsadaraj.c@turtle23.com', true),
  ('Patcharaporn Sayayon (Nan Chopper)', 'Procurement', 'patcharaporn.s@turtle23.com', true),
  ('Uraiwan Julratphan (Wan)', 'Procurement', 'uraiwan.j@turtle23.com', true),
  ('Rawisara Teerapakornkul (Star)', 'Project Management', 'rawisara.t@turtle23.com', true),
  ('Tanapat Noisiri (Nutt)', 'Project Management', 'tanapat.n@turtle23.com', true),
  ('Wassana Laam (Ying)', 'Project Management', 'wassana.l@turtle23.com', true)
on conflict do nothing;
insert into public.contract_types (classification, type, sub_type, sla, active) values
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Agreement / สัญญาเช่า', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement / สัญญาเช่าช่วง', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Asset Agreement / สัญญาเช่าทรัพย์สิน', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Rental Agreement / สัญญาเช่าทั่วไป', 22, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Service Agreement / สัญญาให้บริการ', null, 22, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', null, 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Sale and Purchase Agreement / สัญญาซื้อขาย', null, 24, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Outsourcing Agreement / สัญญาจ้าง', null, 24, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Consultancy Agreement / สัญญาให้คำปรึกษา', 24, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Confidentiality Agreement / สัญญารักษาความลับ', 20, true),
  ('Day-to-day Work / งานดำเนินงานทั่วไป', 'Others / อื่น ๆ', null, 20, true),
  ('Confidential / สัญญาลับ', 'Preliminary Agreement / ข้อตกลงเบื้องต้น', 'Memorandum of Understanding / บันทึกความเข้าใจ', 24, true),
  ('Confidential / สัญญาลับ', 'Preliminary Agreement / ข้อตกลงเบื้องต้น', 'Term Sheet / เอกสารสรุปเงื่อนไขเบื้องต้น', 24, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Consultancy Agreement / สัญญาให้คำปรึกษา', 24, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Confidentiality Agreement / สัญญารักษาความลับ', 20, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement / สัญญาบริหารจัดการ', 24, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Loan Agreement / สัญญาเงินกู้', 28, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Mergers and Acquisitions Agreement / สัญญาการควบรวมและซื้อกิจการ', 28, true),
  ('Confidential / สัญญาลับ', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Shareholders’ Agreement / สัญญาระหว่างผู้ถือหุ้น', 28, true),
  ('Confidential / สัญญาลับ', 'Others / อื่น ๆ', null, 20, true)
on conflict do nothing;
insert into public.action_sla (action, description, sla, rule, active) values
  ('Submit to Review', 'ส่งสัญญาเข้าสู่กระบวนการตรวจสอบ', 7, '7 วันทำการ (เริ่มเมื่อ Add Case)', true),
  ('Return', 'ส่งสัญญากลับเพื่อแก้ไขหรือเพิ่มเติมข้อมูล', 3, '3 วันทำการ (เมื่อได้รับ Return)', true),
  ('Resubmit', 'ส่งสัญญากลับเข้าสู่กระบวนการตรวจสอบอีกครั้งหลังแก้ไข', 5, '5 วันทำการ (เมื่อได้รับ Resubmit)', true),
  ('Forward', 'ส่งต่อสัญญาไปยังหน่วยงานหรือผู้รับผิดชอบลำดับถัดไป', 5, '5 วันทำการ (เมื่อได้รับ Forward)', true)
on conflict do nothing;
insert into public.contracts (id, name, department, owner, classification, type, sub_type, vendor, stage, cycle, returns, station_from, station_to, station_in, add_case_date, due_date, system_due, total_sla, remark, access_level, status) values
  ('CT-N-OP-001', 'Sub Lease Agreement - 3 fl Capri', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement', 'Otto - MPZ', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-21', '2026-04-21', '2026-05-19', '2026-05-19', 20, 'Place: 3 fl Capri | Source Status: In Process | Legal Status: Finalized by Legal | Latest Action: K. Henry will support to talk with K. Otto. | Note: sign quotation instead of agreement', 'Normal', 'Open'),
  ('CT-N-OP-002', 'Lease Asset / Amendment - BLY-T10', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Asset / Amendment', 'BLY-T10', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', '2026-02-05', '2026-03-05', '2026-03-05', 20, 'Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L20-69 | Received: 05 Feb 2026 | Latest Action: Final signing process by OP/will send to K. Todd for signing first. Chef Ton sign back by 12 June 2026 | Note: old period, Not yet received the signed copy. sent to chef Ton 19 Feb', 'Normal', 'Open'),
  ('CT-N-OP-003', 'Sub Lease Agreement - BLY-FSQ', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement', 'BLY-FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-30', '2026-03-30', '2028-10-31', '2026-04-27', 20, 'Source Status: In Process | Legal Status: Awaiting information in SA | Legal Tracking: L64-69 | Received: 30 Mar 2026 | Target: 13 Apr 2026 | Legal Done: 12 Mar 2026 | Latest Action: Chef Ton''s review | Note: new period, 1 Nov 25 - 31 Oct 28', 'Normal', 'Open'),
  ('CT-N-OP-004', 'Sub Lease Agreement - winwin-FSQ', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Sub Lease Agreement', 'winwin-FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-13', '2026-03-13', '2028-10-31', '2026-04-10', 20, 'Source Status: In Process | Legal Status: Awaiting information in SA | Legal Tracking: L48-69 | Received: 13 Mar 2026 | Target: 27 Mar 2026 | Legal Done: 20 Mar 2026 | Latest Action: Sent to Tenant for reviewing./ As checked with K. Gee, he sent to Legal BTS for reviewing. | Note: new period, 1 Nov 25 - 31 Oct 28', 'Normal', 'Open'),
  ('CT-N-OP-005', 'Lease Asset / Amendment - BK Salon', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Asset / Amendment', 'BLY-T3', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-16', '2026-04-16', '2026-05-14', '2026-05-14', 20, 'Place: BK Salon | Source Status: In Process | Legal Status: Awaiting asset information | Legal Tracking: L58-69 | Received: 16 Apr 2026 | Target: 30 Apr 2026 | Latest Action: Final by legal, OP confirm the terms and conditions, Sent to Tenant on 19 June 2026 | Note: the name should b T3, due to the exceution date is on 1 Apr 25 (Back date)', 'Normal', 'Open'),
  ('CT-N-OP-006', 'Lease Asset / Amendment - Gowin', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Asset / Amendment', 'BLY - FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', '2026-02-05', '2026-03-05', '2026-03-05', 20, 'Place: Gowin | Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L22-69 | Received: 05 Feb 2026 | Target: 19 Feb 2026 | Legal Done: 06 Mar 2026 | Latest Action: USER - To send agreement to counterparty', 'Normal', 'Open'),
  ('CT-N-OP-007', 'Lease Agreement - Gowin', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Agreement', 'CM Gold (Jimmy) - FSQ', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-20', '2026-03-20', '2026-04-17', '2026-04-17', 20, 'Place: Gowin | Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L63-69 | Received: 20 Mar 2026 | Target: 03 Apr 2026 | Legal Done: 31 Mar 2026 | Latest Action: USER - To send agreement to counterparty/ Got review from Tenant, will send to Legal on 20May26/ Agreement will be sent by 15 June 2026', 'Normal', 'Open'),
  ('CT-N-OP-008', 'Service - Lawoi''', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service', 'TTH-Grab', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-10', '2026-02-10', '2026-03-12', '2026-03-12', 22, 'Place: Lawoi'' | Source Status: In Process | Legal Status: Awaiting further information | Received: 10 Feb 2026 | Target: 24 Feb 2026 | Legal Done: 10 Feb 2026 | Latest Action: On process of singing, will sent to LAWOI by 24 June 2026', 'Normal', 'Open'),
  ('CT-N-IT-001', 'Reservation System - Kappo S38', 'IT', 'Kawinphop Champee (Boss)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Reservation Service Agreement', 'Weeloy - T5', 'Draft Created', 1, 0, 'Kawinphop Champee (Boss)', 'Siwaporn Iamwiboon (Grace)', '2026-02-23', '2026-02-23', '2026-03-25', '2026-03-25', 22, '- เนื่องจาก memo ที่นำส่งมีการลงนามไม่ครบสมบูรณ์ ดังนั้น ขอให้จัดส่งให้ครบถ้วน
- วันที่ของสัญญาจะขอให้เว้นว่างไว้ 
- ขอให้พิจารณาวันตามข้อ 6.1 ว่ายังเป็นวันเริ่มต้น 11 April 26 อยู่หรือไม่ เนื่องจากเลยระยะเวลาดังกล่าวมาแล้ว
- เนื่องจากมีการนำข้อมูลส่วนบุคคลมาใช้ในหลายส่วน ขอให้ทำแบบ flow การใช้ข้อมูลตามที่กำหนดในสัญญา และแบบฟอร์มการส่งตรวจ pdpa', 'Normal', 'Open'),
  ('CT-N-BD-001', 'Interior Design Agreement - Roaster Coffee', 'Business Development', 'Supakorn Teerawutthiporn (PJ)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Interior Design Agreement', 'T5 - PAC', 'Draft Created', 1, 0, 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-03-19', '2026-03-19', '2026-04-22', '2026-04-22', 24, 'Place: Roaster Coffee | Source Status: In Process | Received: 19 Mar 2026 | Target: 02 Apr 2026 | Latest Action: Final signing process by BD', 'Normal', 'Open'),
  ('CT-N-BD-002', 'No.1749 - Roaster Coffee', 'Business Development', 'Supakorn Teerawutthiporn (PJ)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Lease Agreement', 'T5-WBKK', 'Draft Created', 1, 0, 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-04-30', '2026-04-30', '2026-05-28', '2026-05-28', 20, 'Place: Roaster Coffee | Source Status: In Process | Legal Status: Awaiting further information | Received: 30 Apr 2026 | Latest Action: Final signing process by BD', 'Normal', 'Open'),
  ('CT-N-MKT-001', 'Consultancy Agreement - Unicorn Bldg', 'Marketing', 'Nithita Aroonchote (Ploy)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Consultancy Agreement', 'T23-Kamkoong', 'Draft Created', 1, 0, 'Nithita Aroonchote (Ploy)', 'Nithita Aroonchote (Ploy)', '2026-04-09', '2026-04-09', '2026-05-13', '2026-05-13', 24, 'Place: Unicorn Bldg | Source Status: In Process | Legal Status: Final signing process by MKT | Legal Tracking: L70-69 | Received: 09 Apr 2026 | Target: 23 Apr 2026 | Legal Done: 27 Apr 2026 | Latest Action: Final signing process by MKT', 'Normal', 'Open'),
  ('CT-N-OP-009', 'Laundry Service - Baan Turtle BKK', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Laundry Service', 'PVE-FSQ', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-08', '2026-04-08', '2026-05-08', '2026-05-08', 22, 'Place: Baan Turtle BKK | Source Status: In Process | Legal Status: Finalized by Legal | Received: 08 Apr 2026 | Target: 22 Apr 2026 | Note: K. Koy', 'Normal', 'Open'),
  ('CT-N-ADMIN-001', 'House Keeper - T23 office', 'Administration', 'Nattanai Saranpumidech (Ohm)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement', 'T23-SCS', 'Draft Created', 1, 0, 'Nattanai Saranpumidech (Ohm)', 'Nattanai Saranpumidech (Ohm)', '2026-04-16', '2026-04-16', '2026-05-18', '2026-05-18', 22, 'Place: T23 office | Source Status: In Process | Legal Status: Finalized by Legal | Legal Tracking: L76-69 | Received: 16 Apr 2026 | Target: 30 Apr 2026 | Legal Done: 21 Apr 2026', 'Normal', 'Open'),
  ('CT-N-OP-010', 'Secirity Guard - BK Salon', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement', 'FSQ - LSS', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-24', '2026-04-24', '2026-05-26', '2026-05-26', 22, 'Place: BK Salon | Source Status: In Process | Received: 24 Apr 2026 | Latest Action: sent agreement to supplier for issuing and signing contract by 9 June 2026', 'Normal', 'Open'),
  ('CT-N-MKT-002', 'MKT services - BTSV', 'Marketing', 'Pattarat Piamsin (Mind)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Consultancy Agreement', 'T23 - MCL', 'Draft Created', 1, 0, 'Pattarat Piamsin (Mind)', 'Pattarat Piamsin (Mind)', '2026-05-21', '2026-05-21', '2026-06-24', '2026-06-24', 24, 'Place: BTSV | Source Status: In Process | Received: 21 May 2026', 'Normal', 'Open'),
  ('CT-N-OP-011', 'Lift service - Baan Turtle', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement with equipment', 'FSQ - Cibes', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', '2026-05-25', '2026-06-24', '2026-06-24', 22, 'Place: Baan Turtle | Source Status: In Process | Received: 25 May 2026', 'Normal', 'Open'),
  ('CT-N-OP-012', 'Lift service - Baan Turtle', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Service Agreement without equipment', 'FSQ - Cibes', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', '2026-05-25', '2026-06-24', '2026-06-24', 22, 'Place: Baan Turtle | Source Status: In Process | Received: 25 May 2026', 'Normal', 'Open'),
  ('CT-N-OP-013', 'Equipments - Lawoi''', 'Operation', 'Ratchaneekul Yamkate (Koy)', 'Day-to-day Work', 'Lease & Rental Agreement / สัญญาเช่าและให้เช่า', 'Eqipment lease agreement', 'KTT - Saha', 'Draft Created', 1, 0, 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', '2026-05-25', '2026-06-22', '2026-06-22', 20, 'Place: Lawoi'' | Source Status: In Process | Received: 25 May 2026', 'Normal', 'Open'),
  ('CT-N-MKT-003', 'cross charge', 'Marketing', 'Pijitporn Atjima-anan (Mod)', 'Day-to-day Work', 'Outsourcing Agreement / สัญญาจ้าง', 'Consultancy Agreement', 'T23 - Alpea', 'Draft Created', 1, 0, 'Pijitporn Atjima-anan (Mod)', 'Pijitporn Atjima-anan (Mod)', '2026-06-05', '2026-06-05', '2026-07-09', '2026-07-09', 24, 'Source Status: In Process | Legal Tracking: L100-69 | Received: 05 Jun 2026 | Latest Action: Final signing process by MKT', 'Normal', 'Open'),
  ('CT-N-OP-014', 'Lease Agreement/ Amendment - Baan Turtle', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Amendment Agreement / สัญญาแก้ไขเพิ่มเติม', 'Lease Agreement/ Amendment', 'T23 - T10', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-04', '2026-06-04', '2026-07-02', '2026-07-02', 20, 'Place: Baan Turtle | Source Status: In Process | Received: 04 Jun 2026', 'Normal', 'Open'),
  ('CT-N-OP-015', 'PCS - Baan Turtle Phuket', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Service Agreement / สัญญาให้บริการ', 'Security service agreement', 'T23', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', '2026-06-23', '2026-07-23', '2026-07-23', 22, 'Place: Baan Turtle Phuket | Source Status: In Process | Received: 23 Jun 2026', 'Normal', 'Open'),
  ('CT-N-OP-016', 'Sakeseeker - Capricci', 'Operation', 'Preeyapas Srinon (Nan)', 'Day-to-day Work', 'Commercial Agreement / สัญญาทางธุรกิจ', 'SAKE Playground event', 'Mammapazza', 'Draft Created', 1, 0, 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', '2026-06-23', '2026-07-27', '2026-07-27', 24, 'Place: Capricci | Source Status: In Process | Received: 23 Jun 2026', 'Normal', 'Open'),
  ('CT-C-FIN-001', 'Management Agreement - Sathorn 10 Project', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - FSQ', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Sathorn 10 Project | Source Status: In Process | Legal Tracking: L99-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-002', 'Management Agreement - Baan Turtle', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - FSQ', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Baan Turtle | Source Status: In Process | Legal Tracking: L106-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-003', 'Management Agreement - Sathu Pradit', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - FSQ', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Sathu Pradit | Source Status: In Process | Legal Tracking: L107-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-004', 'Management Agreement - Chan Kao', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - WBKK', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Chan Kao | Source Status: In Process | Legal Tracking: L108-69 | Received: 15 May 2026', 'Confidential', 'Open'),
  ('CT-C-FIN-005', 'Management Agreement - Yenakart', 'Finance', 'Atsanai Banmai (Bank)', 'Confidential', 'Commercial Agreement / สัญญาทางธุรกิจ', 'Management Agreement', 'T23 - WBKK', 'Draft Created', 1, 0, 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', '2026-05-15', '2026-06-18', '2026-06-18', 24, 'Place: Yenakart | Source Status: In Process | Legal Tracking: L109-69 | Received: 15 May 2026', 'Confidential', 'Open')
on conflict do nothing;
insert into public.contract_logs (contract_id, log_no, cycle, action, from_person, to_person, in_date, out_date, sla, reason, approval, updated_by, updated_at) values
  ('CT-N-OP-001', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-21', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-002', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-003', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-30', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-004', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-13', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-005', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-16', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-006', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-05', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-007', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-03-20', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-008', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-02-10', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-IT-001', 1, 1, 'Draft Created', 'Kawinphop Champee (Boss)', 'Siwaporn Iamwiboon (Grace)', '2026-02-23', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-BD-001', 1, 1, 'Draft Created', 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-03-19', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-BD-002', 1, 1, 'Draft Created', 'Supakorn Teerawutthiporn (PJ)', 'Supakorn Teerawutthiporn (PJ)', '2026-04-30', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-MKT-001', 1, 1, 'Draft Created', 'Nithita Aroonchote (Ploy)', 'Nithita Aroonchote (Ploy)', '2026-04-09', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-009', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-04-08', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-ADMIN-001', 1, 1, 'Draft Created', 'Nattanai Saranpumidech (Ohm)', 'Nattanai Saranpumidech (Ohm)', '2026-04-16', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-010', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-04-24', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-MKT-002', 1, 1, 'Draft Created', 'Pattarat Piamsin (Mind)', 'Pattarat Piamsin (Mind)', '2026-05-21', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-011', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-012', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-013', 1, 1, 'Draft Created', 'Ratchaneekul Yamkate (Koy)', 'Ratchaneekul Yamkate (Koy)', '2026-05-25', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-001', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-MKT-003', 1, 1, 'Draft Created', 'Pijitporn Atjima-anan (Mod)', 'Pijitporn Atjima-anan (Mod)', '2026-06-05', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-014', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-04', null, 20, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-002', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-003', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-004', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-C-FIN-005', 1, 1, 'Draft Created', 'Atsanai Banmai (Bank)', 'Atsanai Banmai (Bank)', '2026-05-15', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-015', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', null, 22, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z'),
  ('CT-N-OP-016', 1, 1, 'Draft Created', 'Preeyapas Srinon (Nan)', 'Preeyapas Srinon (Nan)', '2026-06-23', null, 24, 'Draft Created by Production Import', 'OK', 'Production Import', '2026-08-11T09:40:42.165Z')
on conflict do nothing;
insert into public.allowed_domains (domain, default_role) values ('turtle23.com', 'viewer') on conflict do nothing;
-- Everyone in the people list starts as viewer; promote people from Admin Tools.
insert into public.user_access (email, display_name, department, role, active) values
  ('pavarit.i@turtle23.com', 'Pavarit Im-em (Dome)', 'Business Development', 'viewer', true),
  ('supakorn.t@turtle23.com', 'Supakorn Teerawutthiporn (PJ)', 'Business Development', 'viewer', true),
  ('atsanai.b@turtle23.com', 'Atsanai Banmai (Bank)', 'Finance', 'viewer', true),
  ('teerapong.y@turtle23.com', 'Teerapong Yaowalux (Pong)', 'Finance', 'viewer', true),
  ('trithana.n@turtle23.com', 'Trithana Niramis (Golf)', 'Finance', 'viewer', true),
  ('kawinphop.c@turtle23.com', 'Kawinphop Champee (Boss)', 'IT', 'viewer', true),
  ('thotsaporn.p@turtle23.com', 'Thotsaporn Phupha (Ra)', 'IT', 'viewer', true),
  ('nattanai.s@turtle23.com', 'Nattanai Saranpumidech (Ohm)', 'Administration', 'viewer', true),
  ('sarocha.k@turtle23.com', 'Sarocha Khamparnonda (Bee Bee)', 'Administration', 'viewer', true),
  ('siwaporn.i@turtle23.com', 'Siwaporn Iamwiboon (Grace)', 'Legal', 'viewer', true),
  ('chanthipapha.s@turtle23.com', 'Chanthipapha Sopanaphimon (Bow)', 'Marketing', 'viewer', true),
  ('jiraphorn.s@turtle23.com', 'Jiraphorn Sukhasawang (Faii)', 'Marketing', 'viewer', true),
  ('nada.r@turtle23.com', 'Nada Rod-in (Da)', 'Marketing', 'viewer', true),
  ('nithita.a@turtle23.com', 'Nithita Aroonchote (Ploy)', 'Marketing', 'viewer', true),
  ('panphop.u@turtle23.com', 'Panphop Udomsinkul (Pap)', 'Marketing', 'viewer', true),
  ('pattarat.p@turtle23.com', 'Pattarat Piamsin (Mind)', 'Marketing', 'viewer', true),
  ('pijitporn.a@turtle23.com', 'Pijitporn Atjima-anan (Mod)', 'Marketing', 'viewer', true),
  ('saowaros.r@turtle23.com', 'Saowaros Ratchatanawin (Ky)', 'Marketing', 'viewer', true),
  ('preeyapas.s@turtle23.com', 'Preeyapas Srinon (Nan)', 'Operation', 'viewer', true),
  ('ratchaneekul.y@turtle23.com', 'Ratchaneekul Yamkate (Koy)', 'Operation', 'viewer', true),
  ('ritthasap.n@turtle23.com', 'Ritthasap Nutthaachakan (Ning)', 'Operation', 'viewer', true),
  ('jadsadaraj.c@turtle23.com', 'Jadsadaraj Charoeanwerapong (Tong)', 'Procurement', 'viewer', true),
  ('patcharaporn.s@turtle23.com', 'Patcharaporn Sayayon (Nan Chopper)', 'Procurement', 'viewer', true),
  ('uraiwan.j@turtle23.com', 'Uraiwan Julratphan (Wan)', 'Procurement', 'viewer', true),
  ('rawisara.t@turtle23.com', 'Rawisara Teerapakornkul (Star)', 'Project Management', 'viewer', true),
  ('tanapat.n@turtle23.com', 'Tanapat Noisiri (Nutt)', 'Project Management', 'viewer', true),
  ('wassana.l@turtle23.com', 'Wassana Laam (Ying)', 'Project Management', 'viewer', true)
on conflict do nothing;
commit;
