-- Backend permission management after Microsoft Entra ID is linked.
-- Run after 001_schema.sql and 002_seed.sql.
--
-- How a user's Access Level is decided at every Microsoft sign-in:
--   1. If the Entra ID token carries an App Role (or group id) listed in entra_role_mappings,
--      the highest mapped level wins and user_access.source becomes 'entra'.
--   2. Otherwise the level set by an Admin in user_access stays as it is (source 'manual').
--   3. Unknown users from an allowed domain start as that domain's default level.
-- Every change to user_access is written to access_audit.

-- ───────────── Entra App Role / group → Access Level ─────────────
create table public.entra_role_mappings (
  claim_value text primary key,             -- App Role value (e.g. Contract.Admin) or group object id
  role public.app_role not null,
  note text
);

insert into public.entra_role_mappings (claim_value, role, note) values
  ('Contract.Viewer', 'viewer', 'Level 1 · Contract Viewer'),
  ('Contract.User', 'user', 'Level 2 · Contract User'),
  ('Contract.Confidential', 'confidential', 'Level 3 · Confidential User'),
  ('Contract.Admin', 'admin', 'Level 4 · System Administrator')
on conflict do nothing;

alter table public.user_access
  add column if not exists source text not null default 'manual' check (source in ('manual', 'entra', 'domain'));

-- Highest level among the App Roles / groups in the user's Entra token (null when none match).
-- Supabase keeps extra ID-token claims under raw_user_meta_data.custom_claims.
create or replace function public.entra_level_for(meta jsonb)
returns public.app_role language sql stable security definer set search_path = public as $$
  select m.role
  from public.entra_role_mappings m
  where m.claim_value in (
    select jsonb_array_elements_text(coalesce(meta -> 'custom_claims' -> 'roles', meta -> 'roles', '[]'::jsonb))
    union
    select jsonb_array_elements_text(coalesce(meta -> 'custom_claims' -> 'groups', meta -> 'groups', '[]'::jsonb))
  )
  order by public.role_level(m.role) desc
  limit 1
$$;

-- First sign-in: Entra role first, then manual list, then allowed domain; anyone else is refused.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_name text := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(v_email, '@', 1));
  v_entra public.app_role := public.entra_level_for(new.raw_user_meta_data);
  v_default public.app_role;
begin
  if v_entra is not null then
    insert into public.user_access (email, display_name, role, source) values (v_email, v_name, v_entra, 'entra')
    on conflict (email) do update set role = excluded.role, source = 'entra';
  elsif not exists (select 1 from public.user_access where email = v_email) then
    select default_role into v_default from public.allowed_domains where domain = split_part(v_email, '@', 2);
    if v_default is null then
      raise exception 'Email % is not allowed to use this system', v_email;
    end if;
    insert into public.user_access (email, display_name, role, source) values (v_email, v_name, v_default, 'domain');
  end if;
  insert into public.profiles (id, email, display_name, last_sign_in_at)
  values (new.id, v_email, v_name, now());
  return new;
end $$;

-- Later sign-ins: keep the level in step with Entra when the token carries a mapped role.
-- If the role was removed in Entra, an Entra-managed user drops back to the domain default.
create or replace function public.handle_user_sign_in()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_entra public.app_role := public.entra_level_for(new.raw_user_meta_data);
begin
  update public.profiles set last_sign_in_at = new.last_sign_in_at where id = new.id;
  if v_entra is not null then
    update public.user_access set role = v_entra, source = 'entra'
    where email = v_email and (role <> v_entra or source <> 'entra');
  else
    update public.user_access ua set role = coalesce(d.default_role, 'viewer'), source = 'domain'
    from (select default_role from public.allowed_domains where domain = split_part(v_email, '@', 2)) d
    where ua.email = v_email and ua.source = 'entra';
  end if;
  return new;
end $$;

drop trigger if exists on_auth_user_sign_in on auth.users;
create trigger on_auth_user_sign_in
  after update of last_sign_in_at, raw_user_meta_data on auth.users
  for each row execute function public.handle_user_sign_in();

-- ───────────── Audit trail ─────────────
create table public.access_audit (
  id bigint generated by default as identity primary key,
  email text not null,
  action text not null,                      -- added / changed / removed
  old_role public.app_role,
  new_role public.app_role,
  old_active boolean,
  new_active boolean,
  source text,
  changed_by text not null,
  changed_at timestamptz not null default now()
);

create or replace function public.audit_user_access()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_by text := coalesce((select email from public.profiles where id = auth.uid()), 'system / Entra sign-in');
begin
  if tg_op = 'INSERT' then
    insert into public.access_audit (email, action, new_role, new_active, source, changed_by)
    values (new.email, 'added', new.role, new.active, new.source, v_by);
  elsif tg_op = 'UPDATE' and (old.role, old.active) is distinct from (new.role, new.active) then
    insert into public.access_audit (email, action, old_role, new_role, old_active, new_active, source, changed_by)
    values (new.email, 'changed', old.role, new.role, old.active, new.active, new.source, v_by);
  elsif tg_op = 'DELETE' then
    insert into public.access_audit (email, action, old_role, old_active, source, changed_by)
    values (old.email, 'removed', old.role, old.active, old.source, v_by);
  end if;
  return coalesce(new, old);
end $$;

create trigger user_access_audit
  after insert or update or delete on public.user_access
  for each row execute function public.audit_user_access();

-- ───────────── Safety: never lose the last Admin ─────────────
create or replace function public.keep_one_admin()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- only matters when the row being changed or removed was an active Admin
  if old.role = 'admin' and old.active
     and not exists (select 1 from public.user_access where role = 'admin' and active) then
    raise exception 'At least one active Admin must remain';
  end if;
  return null;
end $$;

create constraint trigger user_access_keep_admin
  after update or delete on public.user_access
  deferrable initially deferred
  for each row execute function public.keep_one_admin();

-- An Admin edit to a level marks it as manual, so the screen shows who manages it
create or replace function public.mark_manual_change()
returns trigger language plpgsql as $$
begin
  if auth.uid() is not null and (old.role, old.active) is distinct from (new.role, new.active) and new.source = old.source then
    new.source := 'manual';
  end if;
  return new;
end $$;

create trigger user_access_mark_manual
  before update on public.user_access
  for each row execute function public.mark_manual_change();

-- ───────────── RLS ─────────────
alter table public.entra_role_mappings enable row level security;
alter table public.access_audit enable row level security;
create policy entra_role_mappings_admin on public.entra_role_mappings for all using (public.has_level(4)) with check (public.has_level(4));
create policy access_audit_admin_read on public.access_audit for select using (public.has_level(4));
