-- 005: Import a Production Snapshot (production_snapshot.json) from Admin Tools.
-- Run after 001-004. Safe to run more than once.
--   * keeps every snapshot column that has no column of its own in `details` (jsonb)
--   * adds the Contract Name Template master (contract_templates)
--   * import_snapshot(p): Admin only, adds or updates contracts, logs, due date requests and master data
--     in ONE transaction (all or nothing). Nothing is deleted: a row is matched by its key
--     (Contract ID, Contract ID + Log No, name, ...) and updated, otherwise added.
--     Users & Roles keep their levels; people with a new email are added as Viewer.

alter table public.contracts add column if not exists details jsonb;
alter table public.contract_logs add column if not exists details jsonb;
alter table public.due_date_requests add column if not exists details jsonb;

create table if not exists public.contract_templates (
  id bigint generated by default as identity primary key,
  classification text,
  type_group text,
  sub_type text,
  name text not null,
  selection_label text,
  source_row int,
  type text,
  work_type text,
  contract_id text,
  access_level text,
  category text,
  department text,
  vendor text,
  group_name text,
  fixed_sla int,
  sla_version text,
  remark text,
  active boolean not null default true
);
create unique index if not exists contract_templates_label_key on public.contract_templates (selection_label);
create unique index if not exists contract_logs_contract_log_key on public.contract_logs (contract_id, log_no);
create unique index if not exists contract_types_key on public.contract_types (classification, type, (coalesce(sub_type, '')));
alter table public.contract_templates enable row level security;
drop policy if exists contract_templates_read on public.contract_templates;
drop policy if exists contract_templates_admin_write on public.contract_templates;
create policy contract_templates_read on public.contract_templates for select using (public.has_level(2));
create policy contract_templates_admin_write on public.contract_templates for all using (public.has_level(4)) with check (public.has_level(4));

create or replace function public.import_snapshot(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_added int;
begin
  if not public.has_level(4) then
    raise exception 'Only a System Administrator can import a snapshot';
  end if;
  if jsonb_array_length(coalesce(p -> 'contracts', '[]')) = 0 then
    raise exception 'Snapshot has no contracts';
  end if;

  insert into public.departments (name, code, active)
  select name, coalesce(code, ''), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'departments', '[]')) as x(name text, code text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (name) do update set code = excluded.code, active = excluded.active;

  insert into public.people (name, department, email, line_user_id, active)
  select name, department, nullif(lower(email), ''), nullif(line_user_id, ''), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'people', '[]')) as x(name text, department text, email text, line_user_id text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (name) do update set department = excluded.department, email = excluded.email,
    line_user_id = excluded.line_user_id, active = excluded.active;

  insert into public.contract_types (classification, type, sub_type, sla, active)
  select classification, type, coalesce(sub_type, ''), coalesce(sla, 20), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'contract_types', '[]')) as x(classification text, type text, sub_type text, sla int, active boolean)
  on conflict (classification, type, (coalesce(sub_type, ''))) do update set sub_type = excluded.sub_type, sla = excluded.sla, active = excluded.active;

  insert into public.action_sla (action, description, sla, rule, active)
  select action, description, coalesce(sla, 0), rule, coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'action_sla', '[]')) as x(action text, description text, sla int, rule text, active boolean)
  on conflict (action) do update set description = excluded.description, sla = excluded.sla, rule = excluded.rule, active = excluded.active;

  insert into public.contract_templates (classification, type_group, sub_type, name, selection_label, source_row, type, work_type,
    contract_id, access_level, category, department, vendor, group_name, fixed_sla, sla_version, remark, active)
  select classification, type_group, sub_type, name, selection_label, source_row, type, work_type,
    contract_id, access_level, category, department, vendor, group_name, fixed_sla, sla_version, remark, coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'contract_templates', '[]')) as x(classification text, type_group text, sub_type text, name text,
    selection_label text, source_row int, type text, work_type text, contract_id text, access_level text, category text, department text,
    vendor text, group_name text, fixed_sla int, sla_version text, remark text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (selection_label) do update set classification = excluded.classification, type_group = excluded.type_group,
    sub_type = excluded.sub_type, name = excluded.name, source_row = excluded.source_row, type = excluded.type,
    work_type = excluded.work_type, contract_id = excluded.contract_id, access_level = excluded.access_level,
    category = excluded.category, department = excluded.department, vendor = excluded.vendor, group_name = excluded.group_name,
    fixed_sla = excluded.fixed_sla, sla_version = excluded.sla_version, remark = excluded.remark, active = excluded.active;

  insert into public.contracts (id, name, department, owner, classification, type, sub_type, vendor, stage, cycle, returns,
    station_from, station_to, station_in, add_case_date, due_date, system_due, total_sla, remark, access_level, status,
    closed_at, close_reason, created_by, details)
  select id, name, department, owner, classification, type, sub_type, vendor, coalesce(stage, 'Draft Created'), coalesce(cycle, 1), coalesce(returns, 0),
    station_from, station_to, station_in, coalesce(add_case_date, current_date), due_date, system_due, total_sla, remark,
    coalesce(access_level, 'Normal'), coalesce(status, 'Open'), closed_at, close_reason, null, details
  from jsonb_to_recordset(p -> 'contracts') as x(id text, name text, department text, owner text, classification text, type text,
    sub_type text, vendor text, stage text, cycle int, returns int, station_from text, station_to text, station_in date,
    add_case_date date, due_date date, system_due date, total_sla int, remark text, access_level text, status text,
    closed_at date, close_reason text, details jsonb)
  on conflict (id) do update set name = excluded.name, department = excluded.department, owner = excluded.owner,
    classification = excluded.classification, type = excluded.type, sub_type = excluded.sub_type, vendor = excluded.vendor,
    stage = excluded.stage, cycle = excluded.cycle, returns = excluded.returns, station_from = excluded.station_from,
    station_to = excluded.station_to, station_in = excluded.station_in, add_case_date = excluded.add_case_date,
    due_date = excluded.due_date, system_due = excluded.system_due, total_sla = excluded.total_sla, remark = excluded.remark,
    access_level = excluded.access_level, status = excluded.status, closed_at = excluded.closed_at,
    close_reason = excluded.close_reason, details = excluded.details;

  insert into public.contract_logs (contract_id, log_no, cycle, action, from_person, to_person, in_date, out_date, sla,
    reason, approval, updated_by, updated_at, details)
  select contract_id, log_no, coalesce(cycle, 1), action, from_person, to_person, in_date, out_date, sla,
    reason, approval, updated_by, coalesce(updated_at, now()), details
  from jsonb_to_recordset(coalesce(p -> 'contract_logs', '[]')) as x(contract_id text, log_no int, cycle int, action text,
    from_person text, to_person text, in_date date, out_date date, sla int, reason text, approval text, updated_by text,
    updated_at timestamptz, details jsonb)
  on conflict (contract_id, log_no) do update set cycle = excluded.cycle, action = excluded.action,
    from_person = excluded.from_person, to_person = excluded.to_person, in_date = excluded.in_date, out_date = excluded.out_date,
    sla = excluded.sla, reason = excluded.reason, approval = excluded.approval, updated_by = excluded.updated_by,
    updated_at = excluded.updated_at, details = excluded.details;

  insert into public.due_date_requests (contract_id, requested_due, reason, requested_by, status, created_at, details)
  select contract_id, requested_due, reason, requested_by, coalesce(status, 'Pending'), coalesce(created_at, now()), details
  from jsonb_to_recordset(coalesce(p -> 'due_date_requests', '[]')) as x(contract_id text, requested_due date, reason text,
    requested_by text, status text, created_at timestamptz, details jsonb)
  -- the same request (Request ID) is only added once
  where not exists (select 1 from public.due_date_requests d where d.details ->> 'requestId' = x.details ->> 'requestId');

  -- People in the snapshot can sign in; existing accounts (and their levels) are left as they are
  insert into public.user_access (email, display_name, department, role, active)
  select lower(email), name, department, 'viewer', true
  from public.people
  where email like '%@%'
  on conflict (email) do nothing;
  get diagnostics v_added = row_count;

  return jsonb_build_object(
    'imported_contracts', jsonb_array_length(p -> 'contracts'),
    'imported_logs', jsonb_array_length(coalesce(p -> 'contract_logs', '[]')),
    'contracts', (select count(*) from public.contracts),
    'contract_logs', (select count(*) from public.contract_logs),
    'due_date_requests', (select count(*) from public.due_date_requests),
    'departments', (select count(*) from public.departments),
    'people', (select count(*) from public.people),
    'contract_types', (select count(*) from public.contract_types),
    'contract_templates', (select count(*) from public.contract_templates),
    'action_sla', (select count(*) from public.action_sla),
    'new_users', v_added);
end;
$$;

revoke all on function public.import_snapshot(jsonb) from public, anon;
grant execute on function public.import_snapshot(jsonb) to authenticated;
