-- 008: Master Data, edited directly in the web app (Level 5). Run after 001-007. Safe to run more than once.
-- Nothing is dropped and no data is removed.
--   * Every master table (departments, people, contract_types, action_sla, contract_templates, log_view_columns) gets
--       locked     true when the row was added or changed by hand; Import never overwrites a locked row
--       edited_by  who last changed it by hand,  edited_at  when
--     Untick "Locked" in Master Data to let the next Import update that row again.
--   * master_audit: one entry per added / changed / deleted master row (who, when, before and after, manual or import).
--   * A master row that is still used (by contracts, people, templates, users or logs) cannot be deleted;
--     set Active off instead.
--   * import_snapshot() is the same as in 005, except that it skips locked rows and reports how many were kept.

do $$
declare t text;
begin
  foreach t in array array['departments', 'people', 'contract_types', 'action_sla', 'contract_templates', 'log_view_columns'] loop
    execute format('alter table public.%I add column if not exists locked boolean not null default false', t);
    execute format('alter table public.%I add column if not exists edited_by text', t);
    execute format('alter table public.%I add column if not exists edited_at timestamptz', t);
  end loop;
end $$;

-- ───────────── History of master data changes ─────────────
create table if not exists public.master_audit (
  id bigint generated by default as identity primary key,
  table_name text not null,
  row_key text,
  action text not null check (action in ('insert', 'update', 'delete')),
  source text not null check (source in ('manual', 'import')),
  changed_by text,
  changed_at timestamptz not null default now(),
  before jsonb,
  after jsonb
);
create index if not exists master_audit_table_idx on public.master_audit (table_name, changed_at desc);
alter table public.master_audit enable row level security;
grant select on public.master_audit to authenticated;
drop policy if exists master_audit_read on public.master_audit;
create policy master_audit_read on public.master_audit for select using (public.has_level(4));

create or replace function public.master_row_key(tbl text, r jsonb)
returns text language sql immutable as $$
  select case tbl
    when 'departments' then r ->> 'name'
    when 'people' then r ->> 'name'
    when 'action_sla' then r ->> 'action'
    when 'contract_types' then concat_ws(' | ', r ->> 'classification', r ->> 'type', nullif(r ->> 'sub_type', ''))
    when 'contract_templates' then coalesce(r ->> 'selection_label', r ->> 'name')
    when 'log_view_columns' then concat_ws(' / ', r ->> 'section', r ->> 'key')
    else r ->> 'id' end
$$;

create or replace function public.current_editor()
returns text language sql stable security definer set search_path = public as $$
  select coalesce((select p.email from public.profiles p where p.id = auth.uid()), 'SQL Editor')
$$;

-- Before a write: mark rows changed by hand (not by Import) as locked, with who and when
create or replace function public.master_track()
returns trigger language plpgsql set search_path = public as $$
begin
  if coalesce(current_setting('app.importing', true), 'off') = 'on' then
    if tg_op = 'UPDATE' then
      new.locked := old.locked; new.edited_by := old.edited_by; new.edited_at := old.edited_at;
    end if;
    return new;
  end if;
  if tg_op = 'UPDATE' and (to_jsonb(new) - array['locked', 'edited_by', 'edited_at']) = (to_jsonb(old) - array['locked', 'edited_by', 'edited_at']) then
    return new; -- only the lock was changed
  end if;
  new.edited_by := public.current_editor();
  new.edited_at := now();
  if tg_op = 'INSERT' or new.locked is not distinct from old.locked then
    new.locked := true;
  end if;
  return new;
end $$;

-- After a write: one history entry (unchanged rows are not logged)
create or replace function public.master_audit_log()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  b jsonb := case when tg_op <> 'INSERT' then to_jsonb(old) end;
  a jsonb := case when tg_op <> 'DELETE' then to_jsonb(new) end;
begin
  if tg_op = 'UPDATE' and (a - array['edited_by', 'edited_at']) = (b - array['edited_by', 'edited_at']) then
    return null;
  end if;
  insert into public.master_audit (table_name, row_key, action, source, changed_by, before, after)
  values (tg_table_name, public.master_row_key(tg_table_name, coalesce(a, b)), lower(tg_op),
    case when coalesce(current_setting('app.importing', true), 'off') = 'on' then 'import' else 'manual' end,
    public.current_editor(), b, a);
  return null;
end $$;

-- A row still in use cannot be deleted
create or replace function public.master_guard_delete()
returns trigger language plpgsql security definer set search_path = public as $$
declare n int := 0;
begin
  if tg_table_name = 'departments' then
    select (select count(*) from contracts where department = old.name) + (select count(*) from people where department = old.name)
         + (select count(*) from user_access where department = old.name) + (select count(*) from contract_templates where department = old.name) into n;
  elsif tg_table_name = 'people' then
    select (select count(*) from contracts where old.name in (owner, station_from, station_to))
         + (select count(*) from contract_logs where old.name in (from_person, to_person)) into n;
  elsif tg_table_name = 'contract_types' then
    -- contracts point at the Type of Contract; deleting one sub type is fine while another row keeps that type
    if not exists (select 1 from contract_types t where t.type = old.type and t.id <> old.id) then
      select count(*) from contracts where type = old.type into n;
    end if;
  elsif tg_table_name = 'action_sla' then
    select count(*) from contract_logs where action = old.action into n;
  end if;
  if n > 0 then
    raise exception '% "%" is still used by % record(s). Set Active off instead of deleting.',
      tg_table_name, public.master_row_key(tg_table_name, to_jsonb(old)), n;
  end if;
  return old;
end $$;

do $$
declare t text;
begin
  foreach t in array array['departments', 'people', 'contract_types', 'action_sla', 'contract_templates', 'log_view_columns'] loop
    execute format('drop trigger if exists %I_track on public.%I', t, t);
    execute format('create trigger %I_track before insert or update on public.%I for each row execute function public.master_track()', t, t);
    execute format('drop trigger if exists %I_audit on public.%I', t, t);
    execute format('create trigger %I_audit after insert or update or delete on public.%I for each row execute function public.master_audit_log()', t, t);
    execute format('drop trigger if exists %I_guard_delete on public.%I', t, t);
    execute format('create trigger %I_guard_delete before delete on public.%I for each row execute function public.master_guard_delete()', t, t);
  end loop;
end $$;

-- ───────────── Import: same as 005, but locked (hand-edited) master rows are kept ─────────────
create or replace function public.import_snapshot(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_added int;
  v_locked int;
begin
  if not public.has_level(4) then
    raise exception 'Only a System Administrator can import a snapshot';
  end if;
  -- Rows written below are marked as import (not manual edits) by master_track()
  perform set_config('app.importing', 'on', true);
  if jsonb_array_length(coalesce(p -> 'contracts', '[]')) = 0 then
    raise exception 'Snapshot has no contracts';
  end if;

  insert into public.departments (name, code, active)
  select name, coalesce(code, ''), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'departments', '[]')) as x(name text, code text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (name) do update set code = excluded.code, active = excluded.active
  where not public.departments.locked;

  insert into public.people (name, department, email, line_user_id, active)
  select name, department, nullif(lower(email), ''), nullif(line_user_id, ''), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'people', '[]')) as x(name text, department text, email text, line_user_id text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (name) do update set department = excluded.department, email = excluded.email,
    line_user_id = excluded.line_user_id, active = excluded.active
  where not public.people.locked;

  insert into public.contract_types (classification, type, sub_type, sla, active)
  select classification, type, coalesce(sub_type, ''), coalesce(sla, 20), coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'contract_types', '[]')) as x(classification text, type text, sub_type text, sla int, active boolean)
  on conflict (classification, type, (coalesce(sub_type, ''))) do update set sub_type = excluded.sub_type, sla = excluded.sla, active = excluded.active
  where not public.contract_types.locked;

  insert into public.action_sla (action, description, sla, rule, active)
  select action, description, coalesce(sla, 0), rule, coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'action_sla', '[]')) as x(action text, description text, sla int, rule text, active boolean)
  on conflict (action) do update set description = excluded.description, sla = excluded.sla, rule = excluded.rule, active = excluded.active
  where not public.action_sla.locked;

  insert into public.contract_templates (classification, type_group, sub_type, name, selection_label, source_row, type, work_type,
    contract_id, access_level, category, department, vendor, group_name, fixed_sla, sla_version, remark, active)
  select classification, type_group, sub_type, name, selection_label, source_row, type, work_type,
    contract_id, access_level, category, department, vendor, group_name, fixed_sla, sla_version, remark, coalesce(active, true)
  from jsonb_to_recordset(coalesce(p -> 'contract_templates', '[]')) as x(classification text, type_group text, sub_type text, name text,
    selection_label text, source_row int, type text, work_type text, contract_id text, access_level text, category text, department text,
    vendor text, group_name text, fixed_sla int, sla_version text, remark text, active boolean)
  where coalesce(name, '') <> ''
  on conflict (selection_label) do update set classification = excluded.classification, type_group = excluded.type_group,
    sub_type = excluded.sub_type, name = excluded.name, source_row = excluded.source_row, type = excluded.type,
    work_type = excluded.work_type, contract_id = excluded.contract_id, access_level = excluded.access_level,
    category = excluded.category, department = excluded.department, vendor = excluded.vendor, group_name = excluded.group_name,
    fixed_sla = excluded.fixed_sla, sla_version = excluded.sla_version, remark = excluded.remark, active = excluded.active
  where not public.contract_templates.locked;

  insert into public.contracts (id, name, department, owner, classification, type, sub_type, vendor, stage, cycle, returns,
    station_from, station_to, station_in, add_case_date, due_date, system_due, total_sla, remark, access_level, status,
    closed_at, close_reason, created_by, details)
  select id, name, department, owner, classification, type, sub_type, vendor, coalesce(stage, 'Draft Created'), coalesce(cycle, 1), coalesce(returns, 0),
    station_from, station_to, station_in, coalesce(add_case_date, current_date), due_date, system_due, total_sla, remark,
    coalesce(access_level, 'Normal'), coalesce(status, 'Open'), closed_at, close_reason, null, details
  from jsonb_to_recordset(p -> 'contracts') as x(id text, name text, department text, owner text, classification text, type text,
    sub_type text, vendor text, stage text, cycle int, returns int, station_from text, station_to text, station_in date,
    add_case_date date, due_date date, system_due date, total_sla int, remark text, access_level text, status text,
    closed_at date, close_reason text, details jsonb)
  on conflict (id) do update set name = excluded.name, department = excluded.department, owner = excluded.owner,
    classification = excluded.classification, type = excluded.type, sub_type = excluded.sub_type, vendor = excluded.vendor,
    stage = excluded.stage, cycle = excluded.cycle, returns = excluded.returns, station_from = excluded.station_from,
    station_to = excluded.station_to, station_in = excluded.station_in, add_case_date = excluded.add_case_date,
    due_date = excluded.due_date, system_due = excluded.system_due, total_sla = excluded.total_sla, remark = excluded.remark,
    access_level = excluded.access_level, status = excluded.status, closed_at = excluded.closed_at,
    close_reason = excluded.close_reason, details = excluded.details;

  insert into public.contract_logs (contract_id, log_no, cycle, action, from_person, to_person, in_date, out_date, sla,
    reason, approval, updated_by, updated_at, details)
  select contract_id, log_no, coalesce(cycle, 1), action, from_person, to_person, in_date, out_date, sla,
    reason, approval, updated_by, coalesce(updated_at, now()), details
  from jsonb_to_recordset(coalesce(p -> 'contract_logs', '[]')) as x(contract_id text, log_no int, cycle int, action text,
    from_person text, to_person text, in_date date, out_date date, sla int, reason text, approval text, updated_by text,
    updated_at timestamptz, details jsonb)
  on conflict (contract_id, log_no) do update set cycle = excluded.cycle, action = excluded.action,
    from_person = excluded.from_person, to_person = excluded.to_person, in_date = excluded.in_date, out_date = excluded.out_date,
    sla = excluded.sla, reason = excluded.reason, approval = excluded.approval, updated_by = excluded.updated_by,
    updated_at = excluded.updated_at, details = excluded.details;

  insert into public.due_date_requests (contract_id, requested_due, reason, requested_by, status, created_at, details)
  select contract_id, requested_due, reason, requested_by, coalesce(status, 'Pending'), coalesce(created_at, now()), details
  from jsonb_to_recordset(coalesce(p -> 'due_date_requests', '[]')) as x(contract_id text, requested_due date, reason text,
    requested_by text, status text, created_at timestamptz, details jsonb)
  -- the same request (Request ID) is only added once
  where not exists (select 1 from public.due_date_requests d where d.details ->> 'requestId' = x.details ->> 'requestId');

  -- People in the snapshot can sign in; existing accounts (and their levels) are left as they are
  insert into public.user_access (email, display_name, department, role, active)
  select lower(email), name, department, 'viewer', true
  from public.people
  where email like '%@%'
  on conflict (email) do nothing;
  get diagnostics v_added = row_count;

  select (select count(*) from public.departments where locked) + (select count(*) from public.people where locked)
    + (select count(*) from public.contract_types where locked) + (select count(*) from public.action_sla where locked)
    + (select count(*) from public.contract_templates where locked) into v_locked;
  perform set_config('app.importing', 'off', true);

  return jsonb_build_object(
    'locked_kept', v_locked,
    'imported_contracts', jsonb_array_length(p -> 'contracts'),
    'imported_logs', jsonb_array_length(coalesce(p -> 'contract_logs', '[]')),
    'contracts', (select count(*) from public.contracts),
    'contract_logs', (select count(*) from public.contract_logs),
    'due_date_requests', (select count(*) from public.due_date_requests),
    'departments', (select count(*) from public.departments),
    'people', (select count(*) from public.people),
    'contract_types', (select count(*) from public.contract_types),
    'contract_templates', (select count(*) from public.contract_templates),
    'action_sla', (select count(*) from public.action_sla),
    'new_users', v_added);
end;
$$;

revoke all on function public.import_snapshot(jsonb) from public, anon;
grant execute on function public.import_snapshot(jsonb) to authenticated;
