-- 010: Real email from User Case Action (via the Apps Script web app, Gmail); attachments are in Storage (011)
-- Safe to run more than once. Adds columns and one table; no existing data is changed or removed.
--   * action_sla.attachment_required: Attachment Configuration per Action (Resubmit is always optional in the app)
--   * due_date_requests: requester email, decision remark and supporting documents
--   * email_log: one row per email sent (or failed) from the app, with its requestId
--   * approver_emails(): Level 2+ can address the Due Date approval email to the active Admins
--   * Level 2+ may update logs of contracts they can see (Update Status / Close Case set Out Date on the previous log)

alter table public.action_sla add column if not exists attachment_required boolean not null default false;

alter table public.due_date_requests
  add column if not exists requester_email text,
  add column if not exists decision_remark text,
  add column if not exists attachments jsonb not null default '[]';

create table if not exists public.email_log (
  id bigint generated by default as identity primary key,
  request_id text not null,
  kind text not null,                 -- add_case | update_status | close_case | due_request | due_decision
  contract_id text,
  log_id bigint,
  to_email text,
  cc jsonb not null default '[]',
  subject text,
  attachments jsonb not null default '[]',
  status text not null check (status in ('Sent', 'Failed', 'Cancelled')),
  error text,
  sent_by text,
  created_at timestamptz not null default now()
);
create index if not exists email_log_request on public.email_log (request_id);
create index if not exists email_log_contract on public.email_log (contract_id);
alter table public.email_log enable row level security;
drop policy if exists email_log_insert on public.email_log;
create policy email_log_insert on public.email_log for insert with check (public.has_level(2));
drop policy if exists email_log_read on public.email_log;
create policy email_log_read on public.email_log for select using (
  public.has_level(4) or sent_by = (select p.email from public.profiles p where p.id = auth.uid()));

create or replace function public.approver_emails()
returns table (email text, display_name text) language sql stable security definer set search_path = public as $$
  select ua.email, ua.display_name from public.user_access ua
  where public.has_level(2) and ua.active and ua.role in ('admin', 'root')
  order by ua.role, ua.email
$$;
grant execute on function public.approver_emails() to authenticated;

drop policy if exists logs_update on public.contract_logs;
create policy logs_update on public.contract_logs for update
  using (public.has_level(2) and exists (select 1 from public.contracts c where c.id = contract_id))
  with check (public.has_level(2) and exists (select 1 from public.contracts c where c.id = contract_id));
