-- 012: Email outbox for the send-email Edge Function (replaces the Apps Script endpoint)
-- Safe to run more than once. Adds one table; no existing data is changed.
--   * One row per email, keyed by the requestId the website makes when the Send Email dialog opens.
--     Sending the same requestId again (Retry, double click, lost reply) returns the first result instead of a second email.
--   * status: queued -> sending -> sent | failed (failed can be retried; attempts counts the tries)
--   * Only the Edge Function writes here (service role). People read their own rows; Level 4+ read all.

create table if not exists public.email_outbox (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  kind text,
  contract_id text,
  action text,
  to_email text not null,
  cc jsonb not null default '[]',
  subject text not null,
  body text not null,
  attachments jsonb not null default '[]',   -- [{ path, fileName, fileSize, mimeType }] from the attachments bucket
  delivery text,                             -- attached | links | none
  status text not null default 'queued' check (status in ('queued', 'sending', 'sent', 'failed')),
  attempts int not null default 0,
  provider text,
  provider_message_id text,
  error text,
  sent_by uuid,
  sent_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz
);
create index if not exists email_outbox_contract on public.email_outbox (contract_id);
alter table public.email_outbox enable row level security;
drop policy if exists email_outbox_read on public.email_outbox;
create policy email_outbox_read on public.email_outbox for select using (public.has_level(4) or sent_by = auth.uid());
